### ISSUE TITLE
How to prepare artifacts?

### ISSUE THREAD

**Issue by Mattszczp** [microsoft/navcontainerhelper#1024]
Hi Freddy,
I'd like to try to use the -useArtifacts and -artifactUrl with New-NavContainer or New-NavImage... but I can't find any doc on how to prepare an artifact zip file in correct way. By reading code I've found out that I probably need and .bak file and some kind of manifest.json... but that's all I was able to figure out.

Could you write an article or link me to one on how to use Artifacts with NavContainerHelper?

**Comment by freddydk** [comment]
If you are a partner and you have access to Yammer, you can apply for membership of the Docker Artifacts preview group under DynamicsNavDev. If not, you will need to wait just a little longer.

As you have found out, I am working on making it possible to use artifacts instead of docker images, but that is as far as I can go now.
Within 1-2 weeks I will write up some articles on what you should do to use artifacts instead of docker images.

**Comment by Mattszczp** [comment]
We are a partner, but I don't have access to Yammer group. Sent the request. Thanks.
