### ISSUE TITLE
Deployment fails for 'http://aka.ms/navdeveloperpreviewext' link

### ISSUE THREAD

**Issue by olisterrcf** [Microsoft/navcontainerhelper#109]
Hi, I've tried creating the VM on Azure using the above link.

**Comment by freddydk** [comment]
It would help a lot if you described what went wrong.

**Comment by olisterrcf** [comment]
Hi freddydk,
The issue is while deploying the template, if resource group is selected to be 'Create new Resource group'.
There is error while creating a new Resource Group as follows.
'Deployment to resource group 'navrgbcd365' failed.
Additional details from the underlying API that might be helpful: At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-debug for usage details.'

Using the existing Resource Group gives no issues.

**Comment by freddydk** [comment]
The error seems to be related to your subscription/deployment.
Maybe a conflict, maybe a quota you run into, maybe a bad password, maybe some parameters you specify require something else or maybe something else related to this deployment.
I have no chance of reproducing this problem without spending an extensive amount of hours trying to reproduce.
I will close this issue. If you discover the cause and want to share or you think it is something that should be fixed in the template, please reopen.
