### ISSUE TITLE
Could not authenticate VS Code with UserPassword

### ISSUE THREAD

**Issue by SUD-D365** [microsoft/navcontainerhelper#1092]
I have created a Container with NavContainerHelper with -auth NavUserPassword (bcinsider/bcsandbox-master).
Container created successfully with an error below,
![image](https://user-images.githubusercontent.com/33481576/87018960-a5217800-c1ef-11ea-9838-0b5a20afe2d3.png)

I can access BC WebClient. Now i am started development and tried to download symbols with below launch.json.
So when VS Code asked me to pass Username and password for authentication the server i gave my UserPassword that i used while creating container. So its not taking that credentials and prompting up the authentication window again and again.

![image](https://user-images.githubusercontent.com/33481576/87019290-0c3f2c80-c1f0-11ea-9500-bdb5512f13db.png)

m i doing anything wrong here?

Also the docker extension for VS Code is not showing anything like it does on my local win10 pro system.
![image](https://user-images.githubusercontent.com/33481576/87019616-73f57780-c1f0-11ea-9446-69453c2ddf55.png)

OS : Windows server 2016 data center

Thanks
SUD
@freddydk

**Comment by jwikman** [comment]
Hi @SUD-D365 ,

AuthenticationModes `NavUserPassword` and `UserPassword `are two different things. 

You write that you are using `NavUserPassword `when creating the container, but you have `UserPassword `in your launch.json... Update your launch.json with `NavUserPassword `and you should be fine with connecting from VSCode

Reg. your first error - somewhere in your script you are calling `Setup-NavContainerTestUsers` or `Setup-BCContainerTestUsers`. Since you are using `NavUserPassword`, you need to supply credentials to that function...

Reg. docker connection errors from VSCode - Did you start VSCode with "Run as administrator" (elevated mode)? I think that it's needed when you want to connect to the local docker engine...

**Comment by SUD-D365** [comment]
Hi @jwikman thanks for your comment.
But it seems there is no option for NavUserPassword in launch.json.
Only three authentication are there AAD, Windows,UserPassword.

Thanks
Sud

**Comment by jwikman** [comment]
@SUD-D365 you are right reg. authentication in launch.json, wrote from my memory instead of double checking. (I was mixing up UserPassword with UserName in the server setttings....) I'm sorry about that.

Could you proceed with the other issues?

**Comment by freddydk** [comment]
If I am to look at this, you need to provide script and full output.

**Comment by SUD-D365** [comment]
Closing the issue as it has been resolved!!

Thanks @freddydk
