### ISSUE TITLE
Import-TestToolkitToBcContainer: Microsoft_Tests-SCM.app fails: The socket connection was aborted

### ISSUE THREAD

**Issue by postsaurav** [microsoft/navcontainerhelper#1218]
When i tried to create a Business central container using New-BcContainerWizard with partner license and Business Central 16 sandbox I ended us with below error message.
Later i tried creating a on-prem business central container which also ended with same error.
Later I tried to use Import-TestToolkitToBCContainer and failed with same error message.

**Scripts used to Import TestToolkit and cause the issue**
```
Import-TestToolkitToBcContainer -containerName sauravbc16onprem -testToolkitCountry na
```

**Full output of scripts**
```
WARNING: UnhandledErrorMessage
The socket connection was aborted. This could be caused by an error processing your message or a re
ceive timeout being exceeded by the remote host, or an underlying network resource issue. Local soc
ket timeout was '10675199.02:48:05.4775807'.
at <ScriptBlock>, <No file>: line 12
The socket connection was aborted. This could be caused by an error processing your message or a 
receive timeout being exceeded by the remote host, or an underlying network resource issue. Local 
socket timeout was '10675199.02:48:05.4775807'.
At C:\Program Files\WindowsPowerShell\Modules\BcContainerHelper\1.0.2\ContainerHandling\Invoke-Scr
iptInNavContainer.ps1:39 char:13
+             Invoke-Command -Session $session -ScriptBlock $scriptbloc ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Publish-NAVApp], CommunicationException
    + FullyQualifiedErrorId : System.ServiceModel.CommunicationException,Microsoft.Dynamics.Nav.A 
   pps.Management.Cmdlets.PublishNavApp
    + PSComputerName        : 9ca6a1815f7f4d48c112d88cdee10ffd406a8c50c58d9db54c28a596ec2cfa91
...
```

**Screenshots**
![ERROR Docker](https://user-images.githubusercontent.com/17175721/90329078-2b836380-dfbf-11ea-919f-e5a21336c9df.jpg)

**Additional context**
- does it happen all the time? yes after switching to bccontainerhelper.
- did it use to work? - **Yes it used to work for me with navcontainerhelper**

**Comment by freddydk** [comment]
Always full script and full output please, I cannot see anything from the error alone. I need to see what causes the issue.

Hent Outlook til iOS<https://aka.ms/o0ukef>
________________________________
Fra: Saurav Dhyani <notifications@github.com>
Sendt: Sunday, August 16, 2020 9:23:04 AM
Til: microsoft/navcontainerhelper <navcontainerhelper@noreply.github.com>
Cc: Freddy Kristiansen <Freddy.Kristiansen@microsoft.com>; Assign <assign@noreply.github.com>
Emne: [microsoft/navcontainerhelper] Import-TestToolkitToBcContainer: Microsoft_Tests-SCM.app fails: The socket connection was aborted (#1218)


When i tried to create a Business central container using New-BcContainerWizard with partner license and Business Central 16 sandbox I ended us with below error message.
Later i tried creating a on-prem business central container which also ended with same error.
Later I tried to use Import-TestToolkitToBCContainer and failed with same error message.

Scripts used to Import TestToolkit and cause the issue

Import-TestToolkitToBcContainer -containerName sauravbc16onprem -testToolkitCountry na


Full output of scripts

WARNING: UnhandledErrorMessage
The socket connection was aborted. This could be caused by an error processing your message or a re
ceive timeout being exceeded by the remote host, or an underlying network resource issue. Local soc
ket timeout was '10675199.02:48:05.4775807'.
at <ScriptBlock>, <No file>: line 12
The socket connection was aborted. This could be caused by an error processing your message or a
receive timeout being exceeded by the remote host, or an underlying network resource issue. Local
socket timeout was '10675199.02:48:05.4775807'.
At C:\Program Files\WindowsPowerShell\Modules\BcContainerHelper\1.0.2\ContainerHandling\Invoke-Scr
iptInNavContainer.ps1:39 char:13
+             Invoke-Command -Session $session -ScriptBlock $scriptbloc ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Publish-NAVApp], CommunicationException
    + FullyQualifiedErrorId : System.ServiceModel.CommunicationException,Microsoft.Dynamics.Nav.A
   pps.Management.Cmdlets.PublishNavApp
    + PSComputerName        : 9ca6a1815f7f4d48c112d88cdee10ffd406a8c50c58d9db54c28a596ec2cfa91
...


Screenshots
If applicable, add screenshots to help explain your problem.
[ERROR Docker]<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F17175721%2F90329078-2b836380-dfbf-11ea-919f-e5a21336c9df.jpg&data=02%7C01%7Cfreddy.kristiansen%40microsoft.com%7C5c91ea87fcdc46f8d09108d841b53729%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637331593855465804&sdata=63IlsHCrV4O044b9w3rL1nxlWH7dqTPy3zg2gnYAw%2F0%3D&reserved=0>

Additional context

  *   does it happen all the time? yes after switching to bccontainerhelper.
  *   did it use to work? - Yes it used to work for me with navcontainerhelper

**Comment by postsaurav** [comment]
@freddydk  I just ran the command to import Test toolkit  - 
Import-TestToolkitToBcContainer -containerName sauravbc16onprem -testToolkitCountry na

and error is the attached screenshot above.

**Comment by freddydk** [comment]
When you create the issue it says that you need to specify Scripts used to create container and cause the issue and the full output.

**Comment by freddydk** [comment]
This is likely due to memory - see https://github.com/microsoft/navcontainerhelper/issues/1207
