### ISSUE TITLE
using containers and external database to do upgrade from BC14 to BC16

### ISSUE THREAD

**Issue by davmac1** [microsoft/navcontainerhelper#1277]
Freddy - can I use the container to upgrade an external BC14 database to BC16? 
I am testing the procedures to move custom field and tables to extensions. 
If possible, I would like to use a BC14 container, a BC16 container, and an external database.
The initialization of the BC16 container failed because I have to run the upgrade before it comes up.
Is this a workable approach? If yes, where do I add the upgrade routines and migration.json?

**Comment by git-no** [comment]
**Quick answer: yes, it is feasible.**

I have done upgrades multiple times to BC 15 or BC 16 with Docker containers and bigger external database. In deed, it is recommend to use an external database because of performance reasons.
You need two Docker containers, on for the BC start version and preparations and a second Docker container for the target version.
I do the Docker container creation by navcontainerhelper with the standard database (internal). Then with powershell I swith the s the service tier to the external database or back. You can also suspend / stop the internal SQL service, if you like (memory space). All this is standard procedure (NAV supported): to connect a service tier to an external database (of course you have to create and import a certificate into the service tier and database). Everything of this is scriptable.

Keep in mind to have only one container running at the same time, otherwise you would connect to service tier of different BC versions to the same databse.

From my point of view it is not really navcontainerhelper related. It is BC upgrade procedure with infrastructure handling.

The result of multiple upgrade projects is a grown collection of Powershell scripts, a PS upgrade module on top of navcontanerhelper. With this I am able to automate upgrades also from legacy NAV versions to the latest BC version.

**Comment by freddydk** [comment]
Thanks for replying @git-no - I will close this issue as unrelated to containerhelper.
