### ISSUE TITLE
NavUser password expiration

### ISSUE THREAD

**Issue by ninten** [microsoft/navcontainerhelper#1303]
Hi,

I have some environments and I use the following commands to create each user:

$username = 'ausername';
$password = '********'
$Credential = [PSCredential]::new($username,(ConvertTo-SecureString $password -AsPlainText -Force));
New-NavContainerWindowsUser -containerName Container -credential $Credential
New-NavContainerNavUser -containerName Container -WindowsAccount $username

Everything goes fine, but after some time (maybe a month, still didn't get the exact time) the user is unable to login. The username/password dialogue prompts indefinitely. When I get the user information with the Nav command, everything looks normal: user enabled, expiry date apparently null...

![image](https://user-images.githubusercontent.com/667463/94039969-a9aa0580-fdc8-11ea-9c6d-ea4b22e040d0.png)

When the user complains, we found this workaround solves the issue:

docker.exe exec -it ContainerName net user ausername ********

But the problem will happen again. According to the documentation, the [New-NavContainerWindowsUser](https://github.com/microsoft/navcontainerhelper/blob/master/UserHandling/New-NavContainerWindowsUser.ps1) uses the flag -AccountNeverExpires. Is the password expiring then? Is there any way to avoid this when we create the user or with a general configuration?

Thanks!

**Comment by freddydk** [comment]
Windows authentication is the mother of a lot of problems with containers.
Containers doesn't support joining a domain and only because the user in the container and the user in the domain has the same username and password means that it works.
Now if you change the password on your user on the host, it doesn't sync. to the container and it is "dead", but it lives up again if you set the password on the user in the container.
So yes - that is how it is and there is little we can do about it unfortunately.
My recommendation is to user username password or gMSA.
