### ISSUE TITLE
Bussiness Central Container Issue 

### ISSUE THREAD

**Issue by VAIBHAV-NAGAR** [microsoft/navcontainerhelper#1396]
Hi 

I am unable to access the Container through UI and VS code, container is successfully created 
In UI its giving me the Below error
![image](https://user-images.githubusercontent.com/58846308/96970788-d1100180-1531-11eb-8fba-46734863ba01.png)
in VS code 
![image](https://user-images.githubusercontent.com/58846308/96970864-eedd6680-1531-11eb-9b15-f9b916d6c8bc.png)

Script Used : 

```
$auth = "NavUserPassword"
$credential = New-Object pscredential 'username', (ConvertTo-SecureString -String 'pwd' -AsPlainText -Force)
$containerName = "test"
$licenseFile =".flf"
$artifactUrl = Get-BCArtifactUrl -version 17 -country us -select Latest

New-NavContainer -accept_eula `
                 -containerName $containerName `
                 -artifactUrl $artifactUrl `
                 -Credential $credential `
                 -auth $auth `
                 -updateHosts `
                 -licenseFile $licenseFile 

```
If i am Creating the same container with version 16.5 , the container is successfully created but gives the below error 
![image](https://user-images.githubusercontent.com/58846308/96971097-4380e180-1532-11eb-8ad8-462651aa08ae.png)

It would be great, if someone help me out in this. 
Thanks 
vaibhav

**Comment by freddydk** [comment]
The reason why you cannot connect to the first container is likely a firewall, proxy or vpn issue if you are using the correct url in your browser (you did not provide the url nor the launch.json file content)

The second error looke like you have broken the script before the -credential line and the -credential line wasn't part of the script - instead it becomes a line of itself (see here: https://freddysblog.com/2019/08/04/powershell-for-non-experts/ - search for "The Grave")

please format things with "Insert Code" and please add the output of your scripts and URLs you use if the problem persists.

**Comment by itsme112358** [comment]
Hi Vaibhav, we experience this issue when connecting via VPN to our company network. Since our IT department is bent on not allowing any connections even local ones to containers, the VPN software defines routes on every single network to go through the VPN. 
Consequently if you try to communicate with our containers the connection gets routed to our VPN Gateway. This obviously does not know what to do with the request and you get this exact issue.
We currently disconnect the VPN when we need to work with our containers. In future we will switch development to a VDI since this is not a sustainable solution :/
