### ISSUE TITLE
How to authenticate against the container's web service APIs?

### ISSUE THREAD

**Issue by jhorbulyk** [Microsoft/navcontainerhelper#151]
To the best of my knowledge, the following statements are factually true statements:

- [A container doesn't have its own Active Directory and cannot be joined into an AD.](https://github.com/Microsoft/navcontainerhelper/blob/master/NavContainerHelper.md#setup-windows-authentication-with-the-windows-user-on-the-host-computer) (although [this script which creates Azure Active Directory apps](https://github.com/Microsoft/navcontainerhelper/blob/master/AzureAD/Create-AadAppsForNav.ps1) appears to contradict this slightly.)
- [Authentication against NAV API endpoints must be done by Azure Active Directory](https://docs.microsoft.com/en-us/dynamics-nav/endpoints-apis-for-dynamics) 
- It is possible to authenticate against an API endpoint with windows credentials through something simlar to NTLM which operates bellow the HTTP level but this won't be possible in a production environment.

Which leads to the following question: 
**What is the expected way to authenticate against web service APIs (such as OData) that are exposed by a container?**

Would the following work?
1. Created a Windows VM where the windows users were populated by Active Directory
1. Installed Docker and ran the corresponding commands to set up a Business Central Container where the ports on the container are bound to the ports on the OS.
1. Used the powershell commands to create NAV users which are linked by Windows Authentication to users on the Windows OS which are then transitively linked to AD users.
1. Register OAuth Apps in AD.
1. Have users go through the OAuth login flow, where by providing login credentials to AAD they grant access to the transitively linked Business Central user.

**Comment by jhorbulyk** [comment]
Related: https://github.com/Microsoft/nav-docker/issues/220

**Comment by freddydk** [comment]
You are right - a container doesn't and cannot have its own AD, nor can it be joined to an AD.
You can create AAD Apps (which just really ties a URL together with AAD, so that AAD will allow that URL to get tokens - kind of like ADFS - it doesn't join anything)
You can setup Windows auth. using a hack that has been there since Windows For Workgroups (3.11) - namely that a WIndows User with the same name and same password on two machines are allowed to authenticate. This works for single user setups (Dev/Test). For more advanced setups, Windows auth. can be achieved using gMSA, which requires you to be AD administrator of your AD.
When Setting up NAV with AAD - users are created in the NAV database and linked to an AAD account using the auth. email field - and the AAD app ensures that we can login.
When using Windows VMs I would drop Windows Auth. and use NavUserPassword or AAD.
I am making some changes to the Create-AadAppsForNav now - and will probably create a mechanism, which can replicate AAD users to NAV in Docker using a function.

**Comment by jhorbulyk** [comment]
> You can create AAD Apps (which just really ties a URL together with AAD, so that AAD will allow that URL to get tokens - kind of like ADFS - it doesn't join anything)

What type of App would this be in AAD?  Is it `Enterprise applications`, `App registrations` or `Application proxy` or something else?

**Comment by freddydk** [comment]
App Registrations is what this creates today

**Comment by jhorbulyk** [comment]
Are there any instructions explaining how to set up an App registration that links the URL of a NAV container to an existing AAD (using the Azure UI)?  

If I create an app registration where the homepage is the URL to the server hosting my NAV container, I continue to get an error with 
```
AADSTS50001: The application named <redacted> was not found in the tenant named <redacted>.  This can happen if the application has not been installed by the administrator of the tenant or consented to by any user in the tenant.  You might have sent your authentication request to the wrong tenant.
Trace ID: a7f72d32-b87d-4867-b9bc-c016cbb98a00
Correlation ID: 73ff5eeb-3b2d-4013-940e-65d0681097f0
Timestamp: 2018-06-22 13:18:06Z&state=a58ce281-b1a5-4c32-80ff-324d9326878b
```
which would suggest that I'm not linking the URL with AAD correctly.

*(`<redacted>` are mine)*

**Comment by freddydk** [comment]
I have actually (just 10 minutes ago) rewritten the Create-AadAppsForNav to use AzureAD powershell package instead og AzureRM package, because people were experiencing that the AAD App didn't get created correctly.
NavContainerHelper 0.2.9.6 includes the new method.
I am right now testing the ARM template on the new function - and if you use http://aka.ms/getnav2 you will get an ARM template from the DEV branch of the arm templates.
When I checkin later - it becomes http://aka.ms/getnav
NavContainerhelper 0.2.9.6 also includes a function called Create-AadUsersInNavContainer

**Comment by jhorbulyk** [comment]
What would your ARM template do?

**Comment by freddydk** [comment]
The ARM template spins up a VM in Azure, installs Docker, runs and configures NAV on Docker etc. etc.

**Comment by jhorbulyk** [comment]
Creating resources from the http://aka.ms/getnav ARM template, I still find myself in a situation where connections on the OData port (7048) to the NAV docker image require authentication via NTLM and reject authentication mechanisms attached to the HTTP request.  Is there some way that the NAV instance running inside the docker image can be configured to handle authentication in the same way that a stand alone instance of NAV would (i.e. with OAuth as opposed to NTLM)?

**Comment by freddydk** [comment]
When you create a VM using http://aka.ms/getnav, you will get a landing page - and on that a URL on which you can access Web Services and OData using Basic Authentication.
In general - if a container is created using WIndows Auth, Web Services is NTLM.
If the container is NavUserPassword, Web Services is Username/Password = Basic.
If the container is AAD (AccessControlService) you can even configure oAuth - I haven't done so myself.
If the container is AAD (AccessControlService) and you set the service tier to NavUserPassword you can also connect to web services using basic authentication.
All of this is unrelated to Docker and works in exactly the same way if you install from the DVD.
When you say you attach authentication to the http request - how do you do that?
The most simple C# code works just fine:

var wc = new WebClient();
wc.Credentials = new NetworkCredential(UserName, WsKey);
var result = wc.DownloadString(GetPublicODataBaseUrl()+"CustomerLocation?$format=json");

**Comment by jhorbulyk** [comment]
> When you say you attach authentication to the http request - how do you do that?

In this case, I was attempting to use Basic auth with the NAV Username (with email)/password.  I later found out that I needed to use the NAV Username (without email) and an [access key](https://docs.microsoft.com/en-us/dynamics-nav/how-to--use-an-access-key-for-soap-and-odata-web-service-authentication) as the password.

**Comment by freddydk** [comment]
OK
