### ISSUE TITLE
Add Server Instance Param to New-BCContainer

### ISSUE THREAD

**Issue by mjmatthiesen** [microsoft/navcontainerhelper#1548]
**Describe the issue**
Would be nice to be able to set the instance name rather than being forced to use BC. Helpful when using multiple containers in a vm.

**Comment by freddydk** [comment]
The only place where this would be needed is if you have multiple service tiers in one container - and that is not supported.
If you have multiple containers on a VM you would need to distinguish them (container name, IP address or using traefik).
But... - since NAV containers use NAV and BC containers use BC - it is possible.
If you share a file called ServiceSettings.ps1 in -myscripts with this format:
```
https://github.com/microsoft/nav-docker/blob/master/generic/Run/150-new/ServiceSettings.ps1
```
then that should be used.

**Comment by mjmatthiesen** [comment]
Thanks Freddy. I'll close this issue.

I'm using multiple containers, but find it easier if the service names differ.
