### ISSUE TITLE
[Question] Container name limitation

### ISSUE THREAD

**Issue by fridrichovsky** [microsoft/navcontainerhelper#1674]
PLEASE DO NOT INCLUDE ANY PASSWORDS OR TOKENS IN YOUR ISSUE!!!

**Describe the issue**
I would like to ask about the length limit of the container name.
When creating a container with a name longer than 15 characters, a warning first appears: "WARNING: Container name should not exceed 15 characters".
The created container then crashes with the error "Initialization of container NAMELONGERTHAN15CHARS failed", because when adding to the hosts file, the length is truncated to 15 characters: "Adding NAMELONGERTHAN1 to hosts file".
Is it not possible to allow longer container names? Is there a system limitation?
Thank you for your reply.

**Comment by freddydk** [comment]
I had a lot of issues when using longer than 15 character names back in the days when we started, which is why the 15 character limit is in BcContainerHelper. Some Windows Versions might work - some won't - I don't have the details.
I am afraid that it will add a lot of issues and a ton of hours spend on troubleshooting if I lift the restriction, sorry.

**Comment by fridrichovsky** [comment]
OK, thank you for your response.
