### ISSUE TITLE
Suggestion for Restore-BcDatabaseFromArtifacts 

### ISSUE THREAD

**Issue by gintuoklis** [microsoft/navcontainerhelper#1705]
Hey @freddydk, 

I was testing Restore-BcDatabaseFromArtifacts function recently and found few limitations:

1. it uses `new-navdatabase`, ,which makes it impossible to restore bak files from the URL. (not sure why are u using New-NAVDatabase. perhpaps there's a reason for that)
2. it uses SQLPS module, which is no longer updated by MS ([link](https://docs.microsoft.com/en-us/sql/powershell/run-windows-powershell-steps-in-sql-server-agent?view=sql-server-ver15)). SqlServer is the module that should be used

I wrote similar script which allows me to restore database from my storage url. Perhaps you could integrate it into your scripts?

```
function Restore-Database {
    Param(
        [Parameter(Mandatory = $true)]
        [string] $databaseServer,
        [Parameter(Mandatory = $false)]
        [string] $databaseInstance = "",
        [Parameter(Mandatory = $true)]
        [string] $databaseName,
        [Parameter(Mandatory = $false)]
        [string] $bakFile,
        [Parameter(Mandatory = $false)]
        [string] $NewDataPath,
        [Parameter(Mandatory = $false)]
        [string] $NewLogPath
    )

    Import-Module sqlserver


    $databaseServerInstance = $databaseServer
    if ($databaseInstance) {
        $databaseServerInstance += "\$databaseInstance"
    }

    $relocate = @()
    $dbfiles = Invoke-Sqlcmd -ServerInstance $databaseServerInstance -Database tempdb -Query "RESTORE FILELISTONLY FROM URL='$bakFile';"

    foreach ($dbfile in $dbfiles) {
        $DbFileName = $dbfile.PhysicalName | Split-Path -Leaf
        if ($dbfile.Type -eq 'L') {
            $newfile = $NewLogPath.TrimEnd('\') + '\' + $databaseName + '_' + $dbfile.Type + '_' + $dbfile.FileGroupId + '.ldf'
        }
        else {
            $newfile = $NewDataPath.TrimEnd('\') + '\' + $databaseName + '_' + $dbfile.Type + '_' + $dbfile.FileGroupId + '.mdf'
        }
        $relocate += New-Object Microsoft.SqlServer.Management.Smo.RelocateFile ($dbfile.LogicalName, $newfile)
    }

    Restore-SqlDatabase -ServerInstance $databaseServerInstance -Database $databaseName -BackupFile $bakFile -RelocateFile $relocate
}
```

Example how i run my script:

`Restore-Database -databaseServer '10.0.0.42' -databaseName 'branchname' -bakFile 'https://urlToMyBackup/14.5.35970.0.bak' -NewDataPath 'L:\SQL Data\' -NewLogPath 'N:\SQL Log\'`

My server has stored credentials for urlToMyBackup (in case you wonder regarding authentification)

Best Regards, 
Gintautas

**Comment by freddydk** [comment]
You are right the sqlserver is the PowerShell module to use, but I am actually not using any PowerShell commands from sqlps.

The problem is really that the Export-NavApplication and Remove-NavApplication uses the sql dlls in a hardcoded version (smo, smoextended and more) and the hardcoded version is different for different versions of NAV/BC. In order to safely resolve those to the version you have on your machine, I use smoServer and sqlps to give me that.

So, I am not using a single PowerShell command from sqlps - it just ensures that I can get to smoServer .net type is loaded.

Yes, I might be able to replace New-NavDatabase with a normal Restore-Database, I cannot remember why I used New-NavDatabase, but I would still need smoServer for the switch to multi-tenancy.
