### ISSUE TITLE
dlls are used during compilation but not during publishing

### ISSUE THREAD

**Issue by jonaswre** [microsoft/navcontainerhelper#1782]
PLEASE DO NOT INCLUDE ANY PASSWORDS OR TOKENS IN YOUR ISSUE!!!

**Describe the issue**
.netpackages that are used during the compilation are not used when publishing that app after compiliation. So compilation is successful but publishing fails because dlls are missing.

**Scripts used to create container and cause the issue**
Run-ALPipeline

**Additional context**
Sorry but i cant give the full output since that holds some sensitive stuff.
This is directly after the ascii art : "Publishing Apps"

`Publishing C:\ProgramData\BcContainerHelper\Extensions\....app
dotnet.al(179,14): error AL0451: An assembly named 'Test, Version=1.0.0.0, Culture=neutral, PublicKeyToken=52354234' could not be found in the assembly probing paths 'C:\Program Files\Microsoft Dynamics NAV\170\Service\Add-Ins, C:\Windows\TEMP\Microsoft Dynamics NAV\Add-Ins\17.0.16974.0, C:\Program Files\Microsoft Dynamics NAV\170\Service\, C:\Windows\Microsoft.NET\assembly\'
`
To publish successful ether the probing path needs to include "C:\sources\app\.netpackages" or the dll used during compilation are needed to be copied into the assembly probing paths.

I guess easist would be to just copy the files that could take place in AppHandling\Run-AlPipeline.ps1 line 1037.

**Comment by freddydk** [comment]
Run-AlPipeline is really focused at SaaS - PTEs and AppSource apps, which is why this scenario is not really supported - although I am sure you can make it work.
Run-AlPipeline does use Compile-AppInBcContainer, which by default uses .netpackages when compiling, so that piece will work but in order for the publish to work (and the .net dll to work in your app) you would have to copy the DLLs to the container - and I think you would need to restart the container.

My suggestion would be a slightly different approach.

Before calling Run-AlPipeline, you should put all DLLs you need to use in a one folder (like c:\sources\mydlls).
Then you use this:
```
$bcContainerHelperConfig.defaultNewContainerParameters = @{ "additionalparameters" = @("--volume c:\sources\mydlls:c:\run\Add-Ins\mydlls") }
```
This means that in this PowerShell session, c:\sources\mydlls will be shared as c:\run\Add-ins\mydlls to all subsequent container creations. When a container is created, the contents of c:\run\add-ins will be copied to the service tier add-ins folder before starting the service tier.

**Comment by freddydk** [comment]
Fix Ready + Wont fix = Workaround provided:-)

**Comment by freddydk** [comment]
Did this fix the issue?

**Comment by jonaswre** [comment]
I was aware of that workaround just through somebody else might find the
Issue helpful since this really is a bug. Just not one that will likly
affect lots of people. Would you still accept a PR for this Issue?

Best wishes

**Comment by jonaswre** [comment]
Since I already had a workaround I haven't tried your second Option. My workaround was to copy all Files to the Service Tiers Add-In Folder right after container creation. I never had to restart the container nor the service tier. But copy at the right time would be preferred.

I think the best solution would still be to copy */.netpackages/* to the Add-In folder of the Service Tier. That way Run-AlPipeline would just work for . netpackages.

Would you accept a PR for this Issue? 

Best wishes

**Comment by freddydk** [comment]
A few questions to consider before creating a PR
At what time would you do this?
What would you do if there are 40 app folders? would you copy all 40 .netpackages with the container?
What if the same DLL exists in multiple .netpackages?

**Comment by freddydk** [comment]
I can see your suggestion was to copy the DLLs after line 1037 (I guess easist would be to just copy the files that could take place in AppHandling\Run-AlPipeline.ps1 line 1037.) - I don't think that will work. I think the DLLs must be there when the Service Tier starts.

**Comment by jonaswre** [comment]
> A few questions to consider before creating a PR
> At what time would you do this?
I've been doing it right after New-BcContainer and then restart the service tier
> What would you do if there are 40 app folders? would you copy all 40 .netpackages with the container?
Well you would have to. If you want to deploy all 40 together you would have to make sure there .netpackages work together anyway.
> What if the same DLL exists in multiple .netpackages?
Throw an error and have the developer take care of that.

**Comment by freddydk** [comment]
I assume that the .netpackages are not being built as part of the pipeline, but are checked into the depot or downloaded/copied from somewhere else as part of preparing before running Run-AlPipeline.
Maybe Run-AlPipeline could have a -dotnetPackages parameter in which you could specify an array of dotnet dlls, which would be uploaded the the service tier upon creation.

**Comment by jonaswre** [comment]
I guess that would be best. I can still have the .netpackages in every app. And dont lose the information which app needs which .dlls.
But its up to the developer do decide exactly which dll should be used during publishing. And i've your workflow is to have them in a central zip that could work as well. So maybe using same logic as in installApps would be best?

**Comment by michvllni** [comment]
This is the workaround I use just in case it helps someone:
When creating the container I create a Volume to a DLL Repository where we host our DLLs, which maps into the addins directory (`-v C:\my_dlls:C:\Program Files\Microsoft Dynamics NAV\180\Add-Ins\my_dlls`) and then put this directory into the settings.json of my AL-Project instead of the .netpackages directory.
This way I ensure that I have the same DLLs for both the Publish and the Compile. 
Additionally, I copy the .NET-Assembly inside the container to another Volume (via additionalSetup) to make sure my compile also uses the same .NET-Assemblies as my Publish
