### ISSUE TITLE
Multitenant environment before creating backup should dismount default tenant

### ISSUE THREAD

**Issue by kine** [microsoft/navcontainerhelper#1839]
I am using the backup from the multitenant container (bakFolder parameter se to empty folder) to create database on external SQL. But after restore of the App database and creating new container connected to it, new-bccontainer ends with error in import license part (cannot connect to sql). All that is because the app database have entry for default tenant in the $ndo$tenants table which leads to localhost\SQLEXPRESS server to default tenant which doesn't exists. If I remove that entry, all is ok.

May be question is, to which purpose should be used the backups created from the container. If it could be used to create new App DB on external sql and later connect some tenants to it, the container should dismount all tenants before taking the backup and mount them back after that.

**Comment by freddydk** [comment]
The purpose of the backup is really to restore the databases and then get a fresh container, it isn't really intended to move the databases.
Having said that, we could add a parameter to Backup-BcContainerDatabases (cleanBackup), but I guess it would almost have to do what Export-BcContainerDatabasesAsBacpac is doing - copying the database, cleaning up the copy, backing up the copy.

**Comment by epernst** [comment]
We are right doing this with a different script before we use the Backup-BCContainerDatabases. So this change would be very welcomed.

**Comment by freddydk** [comment]
Looked at this.
I don't think we should add more parameters to New-BcContainer to control this flow, nor do I want to go this on Backup-BcContainerDatabases. The reason the bacpac export does this is that this is used for embed app submissions for saas.

Instead of using bakfolder on the new-bccontainer, you should create the container and use Backup-BcContainerDatabases using:

```
Backup-BcContainerDatabases -bakFolder C:\ProgramData\BcContainerHelper\1
```
This will create 3 bak files:
- app = app database
- default = default tenant
- tenant = tenant template (in a new container this is the same as default)

You can dismount (or remove) tenants first using

```
Get-BcContainerTenants -containerName $containerName | % {
    Remove-BcContainerTenant -containerName $containerName -tenantId $_.Id
}
Backup-BcContainerDatabases -bakFolder C:\ProgramData\BcContainerHelper\2
```

This will create 2 bak files:
- app = app database
- tenant = tenant template (not mounted)

or you can use:

```
Get-BcContainerTenants -containerName $containerName | % {
    Remove-BcContainerTenant -containerName $containerName -tenantId $_.Id -doNotRemoveDatabase
}
Backup-BcContainerDatabases -bakFolder C:\ProgramData\BcContainerHelper\3 -tenant default
```

This will create 2 bak files:
- app = app database
- default = default tenant (not mounted)
