### ISSUE TITLE
[Question] Publish-BuildOutputToAzureFeed usage

### ISSUE THREAD

**Issue by AcererakTheLich** [microsoft/navcontainerhelper#1851]
Hi,

I'm trying to implement DevOps Artifacts storage in my release pipelines using Publish-BuildOutputToAzureFeed.ps1 function.

I faced complexity authenticate through my pipelines to be be able to use "az" command (certainly also due to some lack of knowledge in this domain..).
First error was like :
_ERROR: Failed to update Universal Packages tooling.
2021-03-31T10:00:14.0977634Z  Before you can run Azure ***Ops commands, you need to run the login command(az login if using AAD/MSA identity else az devops login if using PAT token) to setup credentials.  Please see https://aka.ms/azure-devops-cli-auth for more information._

But as a first a remark, the $pat parameter mandatory for this function seems to not be used within the function itself. I expected it was there to authenticate but it does not work. 
I then tried to authenticate from outside the function using $env:AZURE_DEVOPS_EXT_PAT = 'xxxxxxxxxx' and I hope it will be ok now. I'm unfortunately not yet at the end of tests as blocking now on feed scope level. 

Error now is not on authentication anymore but like :  _ERROR: The feed with ID 'xxxxxxxx' doesn't exist._
I suppose this is because we are using Project level feeds and not Organization one.

So my question are 
Would it be possible to add az command --project parameter to Publish-BuildOutputToAzureFeed, this should help us working at Project level feeds instead or Organizational ?

And second one, would it be possible to allow version override while calling Publish-BuildOutputToAzureFeed? Actually the function remove last element from DevOps pipeline initial version, which is fine but doesn't fit our versioning rules. Being able to replace expected version at function call would great and flexible.

Kind regards
Fabrice

**Comment by freddydk** [comment]
adding @jonaswre who created this function

**Comment by jonaswre** [comment]
> But as a first a remark, the $pat parameter mandatory for this function seems to not be used within the function itself. I expected it was there to authenticate but it does not work.
I then tried to authenticate from outside the function using $env:AZURE_DEVOPS_EXT_PAT = 'xxxxxxxxxx' and I hope it will be ok now. I'm unfortunately not yet at the end of tests as blocking now on feed scope level.

Im not sure how that $pat parameter slip in there. Im always just using the env varible I think thats just easier in a pipeline. 
and on local you can just do "az devops login" 

> So my question are
Would it be possible to add az command --project parameter to Publish-BuildOutputToAzureFeed, this should help us working at Project level feeds instead or Organizational ?

Yes I can add that.

> And second one, would it be possible to allow version override while calling Publish-BuildOutputToAzureFeed? Actually the function remove last element from DevOps pipeline initial version, which is fine but doesn't fit our versioning rules. Being able to replace expected version at function call would great and flexible.

Do you want to override in Publish-BuildOutputToAzureFeed? Just have an additional parameter to provide an alternative version? Because if you mean override an exsiting package from azure feed i think thats not possible. Regarding the versioning. Maybe @freddydk  has some friends in the devops team and can give them a hint. Or we need to open UserVoice Idea.

**Comment by jonaswre** [comment]
@AcererakTheLich if you want to continue testing you could set a default project.
az devops configure -d project=NAME_OR_ID

https://docs.microsoft.com/de-de/cli/azure/ext/azure-devops/artifacts/universal?view=azure-cli-latest

**Comment by jonaswre** [comment]
The only issue i have with providing your own version is that there could be multiple apps being published. 

`    Get-Childitem –Path (Join-Path $path "\Apps\*.app") | % {`

I guess i could give you an scriptblock to then let you override that part of the code.
But just passing in one version number would not work

**Comment by AcererakTheLich** [comment]
Would be perfect :-)
Just being able to replace this part by our own downgrade block would be great 
            # Downgrade Version to fit AzureFeed... -.- 
            $appVersion = $appJson.version.split('.')
            $appVersion = $appVersion[0..($appVersion.Length - 2)]
            $appVersion = $appVersion -join '.'
