### ISSUE TITLE
Adding authentication type "UserName"

### ISSUE THREAD

**Issue by TheSwede86** [Microsoft/navcontainerhelper#211]
Hello,

I am wondering when / if the authentication option "UserName" will be available for NAV docker;
https://docs.microsoft.com/en-us/dynamics-nav/users-and-credential-types

When we run:
`docker run -e accept_eula=Y -e auth=UserName microsoft/dynamics-nav`
the credential type is set to "Using NavUserPassword Authentication" instead of using the actual "UserName"-authentication available for non-docker NAV.

Best Regards - TheSwede86

**Comment by TheSwede86** [comment]
The users have clients that are not joined to the domain and authenticate using their AD-credentials.

As per the article:
" Typically, this setting should be used when the Microsoft Dynamics NAV Server computer is part of an authenticating Active Directory domain, but the computer where the Microsoft Dynamics NAV Windows client is installed is not part of the domain."

**Comment by freddydk** [comment]
The problem here is that the Server (container) cannot be domain joined.
Running Windows Auth is only really supported for creating a development container on a laptop and authenticate with your host credentials. This uses the "hack" which has been available since Windows 3.11 that if a user exists on two machines with the same username and password - then they are the same.
If you setup gMSA you will be able to use Windows authentication, but I cannot see that working with multiple users as you explain.
So, to answer your question - I don't see Username as being something we can support - we recommend AAD or NavUserPassword.

**Comment by TheSwede86** [comment]
Thank you very much for your reply and I think we will look into using AAD instead.

**Comment by freddydk** [comment]
Note that the NavContainerHelper includes a function to setup apps in the AAD for authentication (Create-AadAppsForNavContainer I think)
