### ISSUE TITLE
'NextMinor' pulling v20 artifacts

### ISSUE THREAD

**Issue by MikeGlue** [microsoft/navcontainerhelper#2247]
**Describe the issue**
I realize this might not be a BcContainerHelper bug but thought I'd raise this as something is wrong somewhere. When pulling the 'nextminor' artifacts, I'm all of a sudden getting v20 artifacts, which are the same artifacts I get when I use 'nextmajor'.

It should be pulling 19.2 artifacts as the official release artifacts are still 19.1

**Scripts used to create container and cause the issue**
```
$sasToken = "<hidden>"
$artifactUrl = Get-BCArtifactUrl -type Sandbox -select NextMinor -country 'us' -sasToken $sasToken
Write-Host $artifactUrl
```

**Full output of scripts**
```
BcContainerHelper version 3.0.0
BcContainerHelper emits usage statistics telemetry to Microsoft
https://bcinsider.azureedge.net/sandbox/20.0.34282.0/us?<hidden>
```

**Comment by freddydk** [comment]
This problem will auto-resolve on January 3rd where we open for sign-up for 19.2. 19.2 was deliberately delayed due to the holidays.
Then nextminor will then return 19.3

The problem is that the retention policy on the bcinsider storage account caused that 19.2 was deleted before it was shipped causing the algorithm to just grab nextmajor instead - we will probably change the retention policy to 45 days instead of 30 on bcinsider to avoid this problem next year.

**Comment by MikeGlue** [comment]
Confirmed this morning that 'nextminor' is now pulling 19.3 as normal.
