### ISSUE TITLE
18.9 w1 artifact missing

### ISSUE THREAD

**Issue by printvisdevelopment** [microsoft/navcontainerhelper#2305]
When trying to get all artifacts for the 18 w1 major version the 18.9 is missing but there are 2 18.10s
We are using this to generate runtime packages for each version and now we can't release for 18.9 - at least not automatically
**Scripts used to create container and cause the issue**
```
Get-BCArtifactUrl -storageAccount bcartifacts -type onprem -version 18 -country w1 -select All
```

**Full output of scripts**
```
PS C:\Windows\system32> Get-BCArtifactUrl -storageAccount bcartifacts -type onprem -version 18 -country w1 -select All
https://bcartifacts.azureedge.net/onprem/18.0.23013.23795/w1
https://bcartifacts.azureedge.net/onprem/18.1.24822.26330/w1
https://bcartifacts.azureedge.net/onprem/18.2.26217.26490/w1
https://bcartifacts.azureedge.net/onprem/18.3.27240.27480/w1
https://bcartifacts.azureedge.net/onprem/18.4.28601.29139/w1
https://bcartifacts.azureedge.net/onprem/18.5.29545.0/w1
https://bcartifacts.azureedge.net/onprem/18.6.30510.0/w1
https://bcartifacts.azureedge.net/onprem/18.7.31790.0/w1
https://bcartifacts.azureedge.net/onprem/18.8.33031.0/w1
https://bcartifacts.azureedge.net/onprem/18.10.35134.0/w1
```

**Comment by freddydk** [comment]
Sorry for this mess, but we shipped a new 18.9 version, which in the meantime was named 18.10.
If you google Business Central 18.9 you will see:
![image](https://user-images.githubusercontent.com/10775043/153386018-d62548b4-9bb7-4c3b-a7e0-a59a655366d8.png)
and when you click the link, you will see:
![image](https://user-images.githubusercontent.com/10775043/153386131-bc8fe149-7c15-4c20-820e-b644324268e2.png)

Absolutely not ideal.

In the latest BcContainerHelper, if you ask for get-bcartifactUrl -version 18.9 - you get the first 18.10 version above (which is 18.9).

Since artifacts doesn't have a CU number and we always request them by 18.x - this was the best I could do.

**Comment by printvisdevelopment** [comment]
Thanks for the quick reply!

I was getting the -all parameter to get the artifacts dynamically without specifying the CU.
I'll have to find a way around this.

**Comment by freddydk** [comment]
with the -all parameter, you can just index into the returned array and select number [9]
