### ISSUE TITLE
[Question] How to Run-Al-Pipeline with a complex App Dependency Structure?

### ISSUE THREAD

**Issue by matthias-planzer** [microsoft/navcontainerhelper#2574]
PLEASE DO NOT INCLUDE ANY PASSWORDS OR TOKENS IN YOUR ISSUE!!!

**Describe the issue**
We have a project with the following dependency structure:
* AppDependency A: Various pre-compiled Apps
* CompiledApp A: A few Apps that should be compiled with the pipeline
  * Dependency: AppDependency A
* AppDependency B: Various pre-compiled Apps
  * Dependency: Compiled App A + AppDependencyA
* CompiledApp B: A App that should be compiled by the pipeline.
  * Dependency: AppDependency A, AppDependency B, Compiled Apps A

Now according to my knowledge, only the Steps AppDependency A + CompiledApp A are possible.
Is there a way how to do the next steps, if not, is it intended that all four steps will be possible in the future?

**Scripts used to create container and cause the issue**
```
None
```

**Full output of scripts**
```
None
```

**Screenshots**

**Additional context**

**Comment by jonaswre** [comment]
Hi, are you on DevOps or GitHub? 

There is a Command Resolve-DependenciesFromAzureFeed if you use that you can handle any dependency forest, even very nested ones. 

There are only two distinctions. .app files that are stored in the feed or a multi app repo so App A and B compiled together.

I've been using that for a year or so, with almost 100 apps  and a max depth of around 10.

**Comment by freddydk** [comment]
The example above isn't supported in one run with Run-AlPipeline (unless appdependenciesB and compiledappsB is test apps (then you can use TestAppDependencies and testApps)
If you want to use Run-AlPipeline, it sounds like you would have to run it twice, with the output of the first run as dependencies for the second run,

**Comment by jonaswre** [comment]
Ahh yes I miss understood the question. But this should work in one compilation if you put A and B in the same Repo. 

Run-Pipeline should execute boths builds sequentially and you could provide the pre compiled apps ether using Resolve-DependenciesFromAzureFeed or just as a ZIP in the installApps property.

**Comment by freddydk** [comment]
@jonaswre - you are 100% right in what you say, but as I understand the problem - F-H has a dependency on A as well.
Currently the logic in Run-AlPipeline will install all apps in InstallApps before all compiled apps.
I guess this logic could be changed to support the scenario at hand, but currently I don't believe you can.

**Comment by jonaswre** [comment]
Ahhhh okay... 
True thats not possible and I'm not sure how useful this case really is because A will need to be compiled alone so that F-H can be compiled.  This would sort of create a circular dependency not between the apps but between the pipelines. 
I think I would just split A and B into diffrent Repos. The "Fix Ready" Tag ist deserved here.

**Comment by freddydk** [comment]
Yeah, today A would have to be build first and then all output from that used in B.
I guess it would be possible to compile all apps (because the installapps are just places in a symbols folder)
But today, I install installapps in dependency order and then I install compiled apps in dependency order - these two would have to be merged for this scenario to work.

**Comment by jonaswre** [comment]
I still think this would still create a circular dependency between the pipelines

AB needs F
F needs A
A will only be compiled with B which needs F

So even if technically possible I dont think this is really useful in the real world. 

But maybe @matthias-planzer can elaborate a bit why this would be useful.

**Comment by freddydk** [comment]
circular references cannot be done in AL.
A needs C,D,E
F,G,H needs A
B needs A,F,G,H
I think

at this time, 2 pipelines

**Comment by jonaswre** [comment]
I meant it its a circular reference between the pipelines not the apps. 

Pipeline 1 has to build A and B (AB)
Pipeline 2 has to build F (F)

If we start empty, Pipeline 2 cant run because its missing A and Pipeline 1 cant run because B is missing F. The Pipelines depend  on each other but not the apps. This will need to be jump stared somewhere. 

Solution 1: Pipeline 1 compiles B, Pipeline 2 compiles A and F (rearanged)
Solution 2: Pipeline 1 compiles B, Pipeline 2 compiles A, Pipeline 3 compiles (seperated)

**Comment by freddydk** [comment]
I would have 

Pipeline 1: build A (and use C,D,E from other source)
Pipeline 2; build B and use F,G,H (and A,C,D,E)

**Comment by jonaswre** [comment]
The splitted approach is always what I recommend. Only add apps in multi repo if they are very very tightly coupled. (Change in almost certainly mean changes in the other.)

But maybe the author has a good reason to request this. I'm curious.

Until the have a great vacation!
