### ISSUE TITLE
Qn: Connect to default (internal) CRONUS database

### ISSUE THREAD

**Issue by bsr203** [microsoft/navcontainerhelper#2599]
**Describe the issue**
I am learning BC, and like to see the content of the database created (default) within the container. In my windows host machine, I have `Microsoft SQL Server Management Studio` installed. Is there a way to connect the default DB inside the container from the host. Not sure forwarding additional ports helps.

Thanks
bsr.

**Scripts used to create container and cause the issue**

```
$containerName = 'bc14'
$auth = 'UserPassword'
$username = 'bsr'
$password = 'Pas$Word!'
$securePassword = ConvertTo-SecureString -String $password -AsPlainText -Force
$credential = New-Object pscredential $username, $securePassword
$artifactUrl = Get-BcArtifactUrl -type 'OnPrem' -country 'na' -version '14.0.29537.0'
New-BcContainer `
    	-accept_outdated `
    	-accept_eula `
    	-containerName $containerName `
    	-credential $credential `
    	-auth $auth `
    	-artifactUrl $artifactUrl `
    	-isolation hyperv `
    	-memoryLimit 8G `
    	-includeCSIDE `
    	-doNotExportObjectsToText `
	-WebClientPort 8087 `
	-FileSharePort 8780 `
	-ManagementServicesPort 7745 `
	-ClientServicesPort 7746 `
	-SoapServicesPort 7747 `
	-ODataServicesPort 7748 `
	-DeveloperServicesPort 7749 `
    	-updateHosts `
    	-publishPorts @(8087,8780,7745,7746,7747,7748,7749)
```

**Comment by freddydk** [comment]
Please note that the effect of -publishPorts is to publish the container ports on the host so that other people in the network can connect to your container. It is typically only used when using servers to host multiple containers.
If this is not what you want - you can remove all the port parameters and the publishports - and then just use default ports on the container.

SSMS can connect to the container on standard SQL port 1433 - just connect to the container name using SQL Server authentication:
![image](https://user-images.githubusercontent.com/10775043/180051961-1ef7f9c3-af4c-43bb-bc42-e9122a767b2c.png)

**Comment by freddydk** [comment]
You can have multiple containers using the same ports - as long as you don't publish the ports on the host (publishports), then the ports won't clash.

**Comment by freddydk** [comment]
Got it, thanks for explaining.
With that setup you can do as you do (different ports) - or you can run a traefik container on the docker host, which works like a proxy.
But if what you have works for you - that's fine.
