### ISSUE TITLE
suggestion: Copy-NavContainer -sourceContainerName -targetContainerName

### ISSUE THREAD

**Issue by kevindstanley1988** [Microsoft/navcontainerhelper#289]
**Is your feature request related to a problem? Please describe.**
When developing there will be bugs related to data in a database in a docker container. It would be nice to be able to be able to copy the entire container to a new name to have a second developer or consultant debug the issue while still working actively in the original development container.

**Describe the solution you'd like**
Add a new powershell function called Copy-NavContainer with parameters for sourceContainerName and targetContainerName that copies the entire docker container environment and gives it a new name.

**Comment by freddydk** [comment]
I think the suggested behavior is already possible with docker, try:

docker stop test
docker commit test mycontainer
docker start test

To get a private container image called mycontainerimage, which is a copy of your test container.

Now you can

docker run mycontainerimage

or 

New-NavContainer -accept_eula -containerName test2 -imagename mycontainerimage -auth NavUserPassword -Credential $credential -updateHosts

or push the image to a private container registry and pull it on another machine.
Note: when using new-navcontainer with a private image created like this, there might be some of the settings that doesn't work because this is seen as a restart of the container with a new name (you cannot switch to multitenancy would be one thing)
