### ISSUE TITLE
FEATURE REQUEST: Add SSL Cert. Validity Period Property to New-BcContainer

### ISSUE THREAD

**Issue by bernalfr** [microsoft/navcontainerhelper#2913]
PLEASE DO NOT INCLUDE ANY PASSWORDS OR TOKENS IN YOUR ISSUE!!!

**Describe the issue**
Currently, creating a container with the -UseSSL property enabled creates a certificate that is valid for one year.  Once the certificate expires, one must go through the process of importing a new certificate or disposing of the container and replacing it with a new one.

Providing the option in New-BcContainer to specify the validity period for the SSL certificate to a value greater than one year would help delay the frequency of what has become a yearly ritual.

**Scripts used to create container and cause the issue**
New-BcContainer

**Full output of scripts**
N/A

**Screenshots**
N/A

**Additional context**
N/A

**Comment by Hartman-S** [comment]
I have an issue that is similar that I was talking to bernalfr about.  In my case the containers are made without SSL, but the container still expires after a year because of the x.509 base cert expiring after a year.  It would be useful to have an option in Nw-BcContainer to set when that base cert should expire.

The alternative would be a mechanism to make regeneration of certs in containers simpler.

**Comment by freddydk** [comment]
Why would you have containers running for a year?
My recommendation has always been to keep the script used to create the container - not the container, for multiple reasons, but the primary being:
- The Windows version inside the container is old and not updated. Any vulnerabilities are not patched.

Also, if using process isolation, any update to the host can break the container.
If you have data you want to preserve, your database should be in a separate SQL Server (IMO)

**Comment by Hartman-S** [comment]
Containers for BC can be setup and used in different ways for different purposes.  A few reasons for maintaining a container for more than a year include long running projects, specialized test bed needs, or replication of a specific environment for development and testing purposes.  

If one were to maintain such a container, or a series of containers, that doesn't mean they are running for the entirety of their life.   If they are not running all the time, or if they are essentially walled off from external threats, then unpatched vulnerabilities may less relevance.

What I'm suggesting is adding an option that provides more flexibility in some usage scenarios.  That includes the flexibility to "expire" a container's cert in less than a year if security issues are an even more critical concern.  I have had containers break because of an expired cert.  If a tool isn't broken, then it may have a purpose and it can be a waste to get/make a new one.

I appreciate your point about data preservation.  I had the same thought a little while back for something.  It did not really apply to the situation that spawned these posts, but it did leave me pondering the benefits of some changes.

**Comment by freddydk** [comment]
Got it.

What you can do fairly simple is to download the setupCertificate.ps1 script (https://github.com/microsoft/nav-docker/blob/master/generic/Run/SetupCertificate.ps1) to a local file - add the -notAfter parameter to the script and specify the full path of the modified local SetupCertificate.ps1 to -myscripts - then you will override the certificate creation with your own version.
