### ISSUE TITLE
Windows Authentication is not working when database is outside of the container

### ISSUE THREAD

**Issue by codeunitone** [microsoft/navcontainerhelper#2942]
I do want to create a NAV2018 docker container which connects to a NAV database located outside of the container. I want to use Windows Authentication for that.

I'm running following command to do that
```
New-BcContainer `
  -accept_eula `
  -containerName MyTestingContainer `
  -databaseServer 'some.server.somewhere' `
  -databaseInstance '' `
  -databaseName 'AnyDatabase' `
  -artifactUrl (Get-BCArtifactUrl -type OnPrem -country de -version 11.0.46360) `
  -databaseCredential (get-credential) `
  -updateHosts `
  -Credential (get-credential -credential $env:USERNAME)
```

The container is created successful but when I'm opening the Web Client it shows following error message.
You do not have access to Microsoft Dynamics NAV. Verify that you have been set up as a valid user in Microsoft Dynamics NAV.

I can connect to the "external" database via the NST inside that container when I'm creating the container with NavUserNamePassword as authentication method.

Do I misunderstand how the Windows Authentication method is working?

**Comment by freddydk** [comment]
Containers doesn't really support Windows Authentication, as the container cannot be domain joined.
You can use Windows auth to connect to a Business Central instance running Windows authentication, because I create a user in the container, which uses the same username/password as on the host - that has worked since Windows 3.11 - and still does.
You can however not connect to a service outside the container using Windows auth.

**Comment by codeunitone** [comment]
Thanks for the quick reply and clarification.
