### ISSUE TITLE
Get-BcContainerAppRuntimePackage & IncludeSourceInPackageFile

### ISSUE THREAD

**Issue by mikolajsledz** [microsoft/navcontainerhelper#3160]
We have a question about the IncludeSourceInPackageFile parameter in the Get-NavContainerAppRuntimePackage command. How does this parameter relate to the resourceExposurePolicy parameters set in the app.json file?

**Comment by catadumitru** [comment]
You can find the documentation here:
https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-security-settings-and-ip-protection#includesourceinsymbolfile
and here:
https://learn.microsoft.com/en-us/powershell/module/microsoft.dynamics.nav.apps.management/get-navappruntimepackage?view=businesscentral-ps-22#-includesourceinpackagefile

If you set the **includeSourceInSymbolFile** resource policy to **true**, you need to use the **IncludeSourceInPackageFile** parameter on the Get-NavContainerAppRuntimePackage command so that the source code is available through debugging.
There was a bug in previous versions of BC and I believe it will only work from versions **19.10, 20.4** and later.
https://github.com/microsoft/AL/issues/7049

**Comment by mikolajsledz** [comment]
Is the parameter IncludeSourceInPackageFile is overwriting the includeSourceInSymbolFile? Or are there independent from each other?

**Comment by freddydk** [comment]
In the end Get-BcContainerAppRuntimePackage is "just" a wrapper over Get-NavAppRuntimePackage, which has this parameter without a lot of additional description: https://learn.microsoft.com/en-us/powershell/module/microsoft.dynamics.nav.apps.management/get-navappruntimepackage?view=businesscentral-ps-22
But I assume that it is to allow people to debug your app (even though it is from a runtime package)

**Comment by catadumitru** [comment]
> @catadumitru thanks for the answer, but i still have a doubt Is the parameter IncludeSourceInPackageFile is overwriting the includeSourceInSymbolFile? Or are there independent from each other?
includeSourceInSymbolFile = true;  IncludeSourceInPackageFile = true; => You **can** see symbols when debugging a runtime app
includeSourceInSymbolFile = true;  IncludeSourceInPackageFile = false; => You **can't** see symbols when debugging a runtime app
includeSourceInSymbolFile = false;  IncludeSourceInPackageFile = true; => You **can't** see symbols when debugging a runtime app - don't remember testing this scenario, but this is what I would expect

**Comment by freddydk** [comment]
They are independent, a Runtime Package is not a symbols file.
You can download symbols from any app on appsource - and you decide whether or not the source is included for debugging your app.
A Runtime Package is the full app, encrypted, so that you cannot just extract the app file and see the source code, but you can install it. It can have the source code included and again based on your app.json setting you can determine whether the symbol file will contain the source as well.
If you have a runtime package without source and you have includesourceinsymbolFile - then I think that is just ignored.

**Comment by RalleSP86** [comment]
Hi,

I have allready a problem with debugging when I create runtime packages over the command Run-ALPipeline.
There ist no possibilty to set parameter IncludeSourceInPackageFile. 
What can I do, to create debuggable runtime packages over the Run-ALPipeLine command?
In our app.json the parameter allowDebugging and includeSourceInSymbolFile are set to true.
