### ISSUE TITLE
No colors in Run-TestsInNavContainer

### ISSUE THREAD

**Issue by kine** [Microsoft/navcontainerhelper#364]
When I call Run-TestsInNavContainer from VSCode terminal, the result have no colors (is just white). I am expecting that they are lost when transferring the result from the container. Is it solvable? Screenshot:
![image](https://user-images.githubusercontent.com/110221/53496375-3d5b0900-3aa2-11e9-99c0-163b57508338.png)

**Comment by freddydk** [comment]
That is because you are not running as admin. That means that I have to launch the function in the container using docker exec - which means that the colors disappear

Få Outlook til iOS<https://aka.ms/o0ukef>
________________________________
Fra: Kamil Sacek <notifications@github.com>
Sendt: Wednesday, February 27, 2019 6:13:35 AM
Til: Microsoft/navcontainerhelper
Cc: Subscribed
Emne: [Microsoft/navcontainerhelper] No colors in Run-TestsInNavContainer (#364)


When I call Run-TestsInNavContainer from VSCode terminal, the result have no colors (is just white). I am expecting that they are lost when transferring the result from the container. Is it solvable? Screenshot:
[image]<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F110221%2F53496375-3d5b0900-3aa2-11e9-99c0-163b57508338.png&data=02%7C01%7Cfreddy.kristiansen%40microsoft.com%7Cf3aae371bb3446d121a808d69cbdc39c%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636868736178139644&sdata=%2F9%2FyKPsf%2Ba8Ets3VvuEr016Cw%2FqgbDPclIJ9A%2BP9Cyw%3D&reserved=0>
