### ISSUE TITLE
Business Central Web Client Fails to Load After Updating to Windows 24H2

### ISSUE THREAD

**Issue by frottke** [microsoft/navcontainerhelper#3718]
**Issue Description**

The Business Central web client is inaccessible after creating a new container. When accessing the URL in Chrome, Edge, or Firefox, the page remains stuck in a "loading" state. Affected URL:  
`http://bcserver/BC/?page=22&tenant=default` (generated via package and publish in Visual Studio Code).

Publishing app packages to the container works as expected. Restarting IIS and the Business Central service did not resolve the issue.

This problem began after updating to Windows 24H2 (version 10.0.26100). A proper `docker system prune` was performed to rule out Docker-related issues. Docker version -> v4.34.3

**Tested BCContainerHelper Versions**
- 6.0.25
- 6.0.26-preview1247

**Script Used to Create the Container (generated by New-BCContainerWizard)**

```powershell
$containerName = 'bcserver'
$credential = Get-Credential -Message 'Using UserPassword authentication. Please enter credentials for the container.'
$auth = 'UserPassword'
$artifactUrl = Get-BcArtifactUrl -type 'OnPrem' -version '24.2.0.0' -country 'de' -select 'Closest'
New-BcContainer `
    -accept_eula `
    -containerName $containerName `
    -credential $credential `
    -auth $auth `
    -artifactUrl $artifactUrl `
    -updateHosts

**Comment by frottke** [comment]
It's like always, as soon as you create an issue on GitHub you find the solution (in this case rather a workaround). I now create the container with Hyper-V isolation and it works

Feels like a bug to me though.. if not, would be great that understand why it behaves like it does.

**Comment by freddydk** [comment]
I actually switched to use Hyperv on my Windows 11 machine quite some time ago because it is faster and works with https as well - so I didn't notice this problem.

Just tried process isolation and have the same experience as you - I cannot connect to the Web Client.

BTW - timings on my machine creating a multitenant 24.5 sandbox container:

Create container with process isolation takes 451 seconds
Create container with hyperv isolation takes 212 seconds

For now, I will change the default isolation mode to hyperv when running 24H2 - if I figure out why this problem occurs and if I (or somebody else) finds a solution, then we can always modify this.

**Comment by Entreri86** [comment]
Same problem for me on BC OnPrem for 24H2, solved with hyperv

**Comment by kaczm** [comment]
Had unhealthy status on bc containers since yesterday, hyperv worked for me as well

**Comment by SjoerddeClippelaar** [comment]
Does anyone know what is the root cause? Switching to hyperv also worked on our side

**Comment by GrzegorzSzwed** [comment]
Same problem for BC OnPrem 25.3 and adding isolation hyperv helped! Thanks!

`New-BcContainer -accept_eula -containerName $containerName -credential $credential -auth $auth -artifactUrl $artifactUrl -imageName $imageName -includeAL -updateHosts -isolation hyperv`

**Comment by bussik** [comment]
Did anyone find what is the root cause? Process isolation takes less memory.
