### ISSUE TITLE
Strange behavoir with cyrillic chars

### ISSUE THREAD

**Issue by elweilando** [Microsoft/navcontainerhelper#390]
I have a strange behavior with cyrillic chars. If i paste a word with cyrillic chars into cside, it's still cyrillic.
But if I save the object and open it again, the string contains only question marks. Same if I export the file to txt. If I change in the exported file the question marks back to the cyrillic word, I can import the file without issues, but in cside I see only the question marks. Same if i use a text constant.

I need the cyrillic chars to valide content whitin xmlports. How can I save these chars without replacing thru cside?

Is this related to the docker container or to the host?

Image: microsoft/dynamics-nav:2018-cu12-fi
NavContainerhelper 0.5.0.7

**Comment by rdebath** [comment]
This is an old issue with all versions of Nav going back into history. With Version 7 Microsoft switched the Text and Code types from an "Ansi" set to UTF-16 in SQL server, this allows a database to have all reasonable character sets in a single database. BUT they did not make this change to the C/SIDE Objects. With MS/AL the character set in use appears to be UTF-8 so that will eventually be "fixed".

Until then while you can set the database to a particular character set for 8-bit characters it's frequently easier to only use ASCII in C/SIDE objects. The codeunit below shows how you can encode *a very few* non-ASCII characters as thier Unicode codepoints.

If you used a "ru" version of the docker image then it's a bug with the image.
If you need to use the "w1" image your only option for characters outside Codepage 1252 (NOT codepage 1251) is to use numbers like below or static data in setup tables.

```
OBJECT Codeunit 50000 Test chars
{
  OBJECT-PROPERTIES
  {
    Date=19/03/19;
    Time=16:58:22;
    Modified=Yes;
    Version List=;
  }
  PROPERTIES
  {
    OnRun=BEGIN

            FOR I := 1 TO 256+48 DO
            BEGIN
              String[I] := I - 1 + 1024;
            END;

            MESSAGE('%1', String);
          END;

  }
  CODE
  {
    VAR
      String@1000000000 : Text;
      I@1000000001 : Integer;

    BEGIN
    END.
  }
}
```

**Comment by elweilando** [comment]
Thanks @rdebath for this detailed answer. I found in mibuso.com another workaround, to change the system settings for "Language for non-Unicode Programs". But that's not a really an option for us, because one not for this scenario configured developer vm can crush the related objects.

I think the workaround with the static data in setup tables are the best way for us. Thank you.
