### ISSUE TITLE
Issue with New-NavContainer (c:\Run\MainLoop.ps1)

### ISSUE THREAD

**Issue by gintuoklis** [Microsoft/navcontainerhelper#411]
Hey Freddy, 
I receive the following error while creating new container (image mcr.microsoft.com/businesscentral/onprem:cu3):

**Command:**

`
New-NavContainer -accept_eula `
                 -containerName $containerName `
                 -imageName $imageName `
                 -additionalParameters @("--volume $lsinstallationdir\:$localpathoncontainer","--env bakfile=$backupfile", "--env locale=nl-NL") `
                 -includeCSIDE `
                 -doNotExportObjectsToText `
				 -myScripts @($additionalScripts) `
                 -licenseFile $licensefile `
                 -shortcuts Desktop 
`

**Process:**

NavContainerHelper is version 0.5.0.11
Host is Microsoft Windows 10 Pro - 1803
Docker Client Version is 18.09.2
Docker Server Version is 18.09.2
Using image mcr.microsoft.com/businesscentral/onprem:cu3-ltsc2016
Removing container l-13-04-release
Removing C:\ProgramData\NavContainerHelper\Extensions\l-13-04-release
Creating Nav container l-13-04-release
Using license file C:\WorkDocs\Licenses\BC License5471945.flf
Version: 13.3.27233.0-W1
Generic Tag: 0.0.9.3
Container OS Version: 10.0.14393.2848 (ltsc2016)
Host OS Version: 10.0.17134.677 (1803)
The container operating system does not match the host operating system, forcing hyperv isolation.
Using hyperv isolation
Creating container l-13-04-release from image mcr.microsoft.com/businesscentral/onprem:cu3-ltsc2016
25509de591f9468d267fe29f09bfc4b216ec0f99aecbc24dfad20fec177e12e9
Waiting for container l-13-04-release to be ready
Initializing...
Starting Container
Hostname is l-13-04-release
PublicDnsName is l-13-04-release
Using Windows Authentication
Starting Local SQL Server
Starting Internet Information Server

**Errror:**
`
docker : . : The term 'c:\Run\MainLoop.ps1' is not recognized as the name of a cmdlet, 
At C:\Program Files\WindowsPowerShell\Modules\navcontainerhelper\0.5.0.11\ContainerHandling\Wait-NavContainerReady.ps1:33 char:21
+             $logs = docker logs $containerName
+                     ~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (. : The term 'c...e of a cmdlet, :String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
`
Any Advice?

Gintautas

**Comment by freddydk** [comment]
What is the value of additionalscripts?

Få Outlook til iOS<https://aka.ms/o0ukef>
________________________________
Fra: Gintautas <notifications@github.com>
Sendt: Monday, April 8, 2019 6:58:28 PM
Til: Microsoft/navcontainerhelper
Cc: Subscribed
Emne: [Microsoft/navcontainerhelper] Issue with New-NavContainer (c:\Run\MainLoop.ps1) (#411)


Hey Freddy,
I receive the following error while creating new container:

Command:

New-NavContainer -accept_eula
-containerName $containerName -imageName $imageName
-additionalParameters @("--volume $lsinstallationdir:$localpathoncontainer","--env bakfile=$backupfile", "--env locale=nl-NL") -includeCSIDE
-doNotExportObjectsToText -myScripts @($additionalScripts)
-licenseFile $licensefile -shortcuts Desktop

Process:

NavContainerHelper is version 0.5.0.11
Host is Microsoft Windows 10 Pro - 1803
Docker Client Version is 18.09.2
Docker Server Version is 18.09.2
Using image mcr.microsoft.com/businesscentral/onprem:cu3-ltsc2016
Removing container l-13-04-release
Removing C:\ProgramData\NavContainerHelper\Extensions\l-13-04-release
Creating Nav container l-13-04-release
Using license file C:\WorkDocs\Licenses\BC License5471945.flf
Version: 13.3.27233.0-W1
Generic Tag: 0.0.9.3
Container OS Version: 10.0.14393.2848 (ltsc2016)
Host OS Version: 10.0.17134.677 (1803)
The container operating system does not match the host operating system, forcing hyperv isolation.
Using hyperv isolation
Creating container l-13-04-release from image mcr.microsoft.com/businesscentral/onprem:cu3-ltsc2016
25509de591f9468d267fe29f09bfc4b216ec0f99aecbc24dfad20fec177e12e9
Waiting for container l-13-04-release to be ready
Initializing...
Starting Container
Hostname is l-13-04-release
PublicDnsName is l-13-04-release
Using Windows Authentication
Starting Local SQL Server
Starting Internet Information Server

Errror:
`
docker : . : The term 'c:\Run\MainLoop.ps1' is not recognized as the name of a cmdlet,
At C:\Program Files\WindowsPowerShell\Modules\navcontainerhelper\0.5.0.11\ContainerHandling\Wait-NavContainerReady.ps1:33 char:21

  *

        $logs = docker logs $containerName


  *

                ~~~~~~~~~~~~~~~~~~~~~~~~~~


     *   CategoryInfo : NotSpecified: (. : The term 'c...e of a cmdlet, :String) [], RemoteException
     *   FullyQualifiedErrorId : NativeCommandError
`
Any Advice?

Gintautas

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMicrosoft%2Fnavcontainerhelper%2Fissues%2F411&data=02%7C01%7Cfreddy.kristiansen%40microsoft.com%7Cbc5bfc88953e4292254a08d6bc436cde%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636903395107386704&sdata=J1syIkhCzqy44ucCaPpiWVzj1aUWcsFodTwvEoeNF%2Bs%3D&reserved=0>, or mute the thread<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAKRqAwuzL2BKH-RZE4NletNLkFdw5Kmwks5ve3U0gaJpZM4ciqOs&data=02%7C01%7Cfreddy.kristiansen%40microsoft.com%7Cbc5bfc88953e4292254a08d6bc436cde%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636903395107386704&sdata=Q1ilzY0A2A819JObXH%2B6BdnS7OIDAUtXb%2Bgy%2FwZNGbw%3D&reserved=0>.

**Comment by gintuoklis** [comment]
Additional scripts just contains some code to install additional LS components.
I know that I don't reach that code since. Otherwise it would have wrote some messages to host. 
If i remove additionalscripts part, i receive the same error. but this time it prints extra line regarding backupfile


....
Using Database .bak file 'c:\temp\Application\w1-ls-central-13-04-release.bak'

docker : . : The term 'c:\Run\MainLoop.ps1' is not recognized as the name of a cmdlet, 
At C:\Program Files\WindowsPowerShell\Modules\navcontainerhelper\0.5.0.11\ContainerHandling\Wait-NavContainerReady.ps1:33 char:21
+             $logs = docker logs $containerName
+                     ~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (. : The term 'c...e of a cmdlet, :String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError

**Comment by gintuoklis** [comment]
It was false alarm @freddydk,
The cause was lack of disk space on my drive :)
Will close the case

**Comment by AbsolutelyFreeWeb** [comment]
@gintuoklis thanks for creating this issue though. I'm getting the exact same error message, and your comment about disk space made me realize my disk space has run out as well.
