### ISSUE TITLE
UnPublish-NavContainerApp gives a little bit to much infomation on "error"

### ISSUE THREAD

**Issue by mheijkant** [Microsoft/navcontainerhelper#415]
Just a remark or suggestion...

Can you tell me if following message-line is intentional when command UnPublish-NavContainerApp is run and when my extension is not available:

My command-line:             
UnPublish-NavContainerApp `
                -containerName $containerName `
                -appName $app.Name `
                -publisher $app.Publisher `
                -version $app.Version `
                -unInstall

This message follows:
Uninstalling <extension> from tenant default
Unpublishing <extension>
Cannot find the extension <extension> because it is not published.
at <ScriptBlock>, <No file>: line 9

I'm wondering if last line "at <ScriptBlock>, <No file>: line 9" is intentional, because I didn't notice this in previous versions.

**Comment by freddydk** [comment]
Are you running as administrator or as non-admin?

**Comment by freddydk** [comment]
You are running as administrator:-)
I found that erroractioinpreference was continue in invoke-scriptinnavcontainer - it should be stop (this is why it prints unpublishing - even though the error comes during uninstall)

The at , : line 9 on my machine says:
at <scriptblock>, <nofile>: line 9
That is the strack trace of the error in order to troubleshoot.
but the error shows twice - I will remove one (but keep the stacktrace)

**Comment by mheijkant** [comment]
Yes, I'm running as administrator.
Github indeed removed the tags.
Thanks for this "small" improvement.
