### ISSUE TITLE
Windows Authentication Password Changed

### ISSUE THREAD

**Issue by andrecavalcanti** [Microsoft/navcontainerhelper#445]
Hi,

I created a 2018 CU8 container with windows authentication. My password changed due to company policy. Now I cannot access any containers. Is there a way to change my password inside the containers?

![image](https://user-images.githubusercontent.com/6551266/57162502-6e1a3000-6dbc-11e9-9567-90080bc01b07.png)

**Comment by freddydk** [comment]
Windows authentication works because the container has a copy of the user and you will have to change the password in the container as well - or renew the container (I always do the latter - containers should always be recreatable (if that is a word))
https://www.petri.com/how-to-change-user-password-with-powershell tells you how to change the password (you need to open a powershell prompt in the container) - I have never tried to do this.

**Comment by andrecavalcanti** [comment]
Thanks
That one worked like a charm!!!
I can open the container now.
I use this container for development. So I modify the objects and generate the AL from it. If I recreate the container as you proposed, Will the objects be overwritten?

Get-WmiObject win32_useraccount | Foreach-Object {
([adsi](“WinNT://”+$_.caption).replace(“\”,”/”)).SetPassword(“FluxCapacitor!11-5-1955”)
}

**Comment by freddydk** [comment]
Yes, recreating the container will replace the database (unless you place the database outside the container).

**Comment by andrecavalcanti** [comment]
I get it. Thanks very much!!!!!
