### ISSUE TITLE
ForceHandleTrackingEvent failed to acquire a lock

### ISSUE THREAD

**Issue by Bssivivek** [microsoft/navcontainerhelper#488]
Hi,
I created new container using below command

**New-NavContainer -containerName SBS -accept_eula -auth NavUserPassword -imageName mcr.microsoft.com/businesscentral/sandbox:us-ltsc2019 -includeCSide -licenseFile "C:\Work\SB-D365BC.flf" -updateHosts**

I some times get below error message when i try to wither download the symbol or when i publish my app
![image](https://user-images.githubusercontent.com/38437776/59299858-8e9e9b00-8c42-11e9-9d60-f4b178f0be08.png)

I am not able to reproduce this issue every time but i am getting this error most of the time when i try to publish the app.

THis happens

1) After in downloaded the latest image
2) I started including Cside because i want to modify the license to test permissions.

Please help!!

**Comment by Bssivivek** [comment]
I also tried restarting my work station but iam still getting the same error.

**Comment by freddydk** [comment]
@atoader - do you know what this is?

**Comment by freddydk** [comment]
Just heard from the team that this is a bug, which we are working to solve. In the mean time, you can change the MetadataLockTimeout setting in customsettings.config to "00:10:00".

This can be done during creation of the container using:

-additionalParameters @("--env CustomNavSettings=MetadataLockTimeout=""00:10:00""")

**Comment by Bssivivek** [comment]
@freddydk thanks a lot and that resolve the issue.

**Comment by PravinDangar** [comment]
@freddydk 

I am facing same issue when publishing to BC Cloud. Whats solution ? Please, Guide me.

**Comment by freddydk** [comment]
@PravinDangar - if you are getting this issue when publishing to BC Cloud it sounds more like a support case, not something to do with docker or containerhelper, sorry.

**Comment by Ajageavi** [comment]
Getting Error in upgarde of BC 15.4 to 16 on Saas, 

NST Tenant State: OperationalWithSyncPendingNST Tenant Detailed State: The extension 'Application by Microsoft 16.0.11240.11946' has a newer version than the the current schema version '15.4.41023.41400'. Run Sync-NavApp to update the schema.The extension '_Exclude_AnonymizedDataSharing_ by Microsoft 16.0.11240.11946' has a newer version than the the current schema version '15.4.41023.41345'. Run Sync-NavApp to update the schema.The extension 'Essential Business Headlines by Microsoft 16.0.11240.11946' has a newer version than the the current schema version '15.4.41023.41345'. Run Sync-NavApp to update the schema.The extension 'Intelligent Cloud Base by Microsoft 16.0.11240.11946' has a newer version than the the current schema version '15.4.41023.41345'. Run Sync-NavApp to update the schema.The extension 'Business Central Intelligent Cloud by Microsoft 16.0.11240.11946' has a newer version than the the current schema version '15.4.41023.41345'. Run Sync-NavApp to update the schema.The extension 'Late Payment Prediction by Microsoft 16.0.11240.11946' has a newer version than the the current schema version '15.4.41023.41345'. Run Sync-NavApp to update the schema.The extension 'Business Central Cloud Migration - Previous Release by Microsoft 16.0.11240.11946' has a newer version than the the current schema version '15.4.41023.41345'. Run Sync-NavApp to update the schema.The extension '_Exclude_APIV1_ by Microsoft 16.0.11240.11946' has a newer version than the the current schema version '15.4.41023.41345'. Run Sync-NavApp to update the schema.The extension '_Exclude_ClientAddIns_ by Microsoft 16.0.11240.11946' has a newer version than the the current schema version '15.4.41023.41345'. Run Sync-NavApp to update the schema.The extension 'Sales and Inventory Forecast by Microsoft 16.0.11240.11946' has a newer version than the the current schema version '15.4.41023.41345'. Run Sync-NavApp to update the schema.The extension 'Microsoft Pay Payments by Microsoft 16.0.11240.11946' has a newer version than the the current schema version '15.4.41023.41345'. Run Sync-NavApp to update the schema.The extension 'PayPal Payments Standard by Microsoft 16.0.11240.11946' has a newer version than the the current schema version '15.4.41023.41345'. Run Sync-NavApp to update the schema.The extension '_Exclude_Microsoft Dynamics 365 - SmartList by Microsoft 16.0.11240.11946' has a newer version than the the current schema version '15.4.41023.41345'. Run Sync-NavApp to update the schema.The extension 'Send remittance advice by email by Microsoft 16.0.11240.11946' has a newer version than the the current schema version '15.4.41023.41345'. Run Sync-NavApp to update the schema.The extension '_Exclude_SyncBaseApp_ by Microsoft 16.0.11240.11946' has a newer version than the the current schema version '15.4.41023.41345'. Run Sync-NavApp to update the schema.Message: Extension 'Application' version 16.0.11240.11946 by 'Microsoft' failed to synchronize the database schema.ForceHandleTrackingEvent failed to acquire a lock Extension '_Exclude_AnonymizedDataSharing_' version 16.0.11240.11946 by 'Microsoft' failed to synchronize the database schema.Cannot synchronize the extension because no synchronized extension could be found to satisfy the dependency definition for Application by Microsoft 16.0.0.0. Extension 'English language (Australia)' version 16.0.11240.11946 by 'Microsoft' failed to synchronize the database schema.ForceHandleTrackingEvent failed to acquire a lock Extension 'Essential Business Headlines' version 16.0.11240.11946 by 'Microsoft' failed to synchronize the database schema.Cannot synchronize the extension because no synchronized extension could be found to satisfy the dependency definition for Application by Microsoft 16.0.0.0. Extension 'Intelligent Cloud Base' version 16.0.11240.11946 by 'Microsoft' failed to synchronize the database schema.ForceHandleTrackingEvent failed to acquire a lock Extension 'Business Central Intelligent Cloud' version 16.0.11240.11946 by 'Microsoft' failed to synchronize the database schema.Cannot synchronize the extension because no synchronized extension could be found to satisfy the dependency definition for Intelligent Cloud Base by Microsoft 16.0.0.0. Extension 'Late Payment Prediction' version 16.0.11240.11946 by 'Microsoft' failed to synchronize the database schema.Cannot synchronize the extension because no synchronized extension could be found to satisfy the dependency definition for Application by Microsoft 16.0.0.0. Extension 'Business Central Cloud Migration - Previous Release' version 16.0.11240.11946 by 'Microsoft' failed to synchronize the database schema.Cannot synchronize the extension because no synchronized extension could be found to satisfy the dependency definition for Intelligent Cloud Base by Microsoft 16.0.0.0. Extension '_Exclude_APIV1_' version 16.0.11240.11946 by 'Microsoft' failed to synchronize the database schema.Cannot synchronize the extension because no synchronized extension could be found to satisfy the dependency definition for Application by Microsoft 16.0.0.0. Extension '_Exclude_ClientAddIns_' version 16.0.11240.11946 by 'Microsoft' failed to synchronize the database schema.Cannot synchronize the extension because no synchronized extension could be found to satisfy the dependency definition for Application by Microsoft 16.0.0.0. Extension 'Send To Email Printer' version 16.0.11240.11946 by 'Microsoft' failed to synchronize the database schema.Cannot synchronize the extension because no synchronized extension could be found to satisfy the dependency definition for Application by Microsoft 16.0.0.0. Extension 'Sales and Inventory Forecast' version 16.0.11240.11946 by 'Microsoft' failed to synchronize the database schema.Cannot synchronize the extension because no synchronized extension could be found to satisfy the dependency definition for Application by Microsoft 16.0.0.0. Extension 'Microsoft Pay Payments' version 16.0.11240.11946 by 'Microsoft' failed to synchronize the database schema.Cannot synchronize the extension because no synchronized extension could be found to satisfy the dependency definition for Application by Microsoft 16.0.0.0. Extension 'PayPal Payments Standard' version 16.0.11240.11946 by 'Microsoft' failed to synchronize the database schema.Cannot synchronize the extension because no synchronized extension could be found to satisfy the dependency definition for Application by Microsoft 16.0.0.0. Extension '_Exclude_Microsoft Dynamics 365 - SmartList' version 16.0.11240.11946 by 'Microsoft' failed to synchronize the database schema.Cannot synchronize the extension because no synchronized extension could be found to satisfy the dependency definition for Application by Microsoft 16.0.0.0. Extension 'Send remittance advice by email' version 16.0.11240.11946 by 'Microsoft' failed to synchronize the database schema.Cannot synchronize the extension because no synchronized extension could be found to satisfy the dependency definition for Application by Microsoft 16.0.0.0. Extension '_Exclude_SyncBaseApp_' version 16.0.11240.11946 by 'Microsoft' failed to synchronize the database schema.Cannot synchronize the extension because no synchronized extension could be found to satisfy the dependency definition for Application by Microsoft 16.0.0.0.
--


These are MS extension and having issue in production environment.


now i uninstalled Extension and upgrading it  with 16.0 then getting error  
SchemaUpdateMode=synchronize&DependencyPublishingOption=default failed with code UnprocessableEntity. Reason: ForceHandleTrackingEvent failed to acquire a lock error

**Comment by freddydk** [comment]
For issues with production tenants online, please create a support ticket.
