### ISSUE TITLE
Cannot find path 'C:\NAVDVD\ModernDev\program files\Microsoft Dynamics NAV' because it does not exist.

### ISSUE THREAD

**Issue by GreatScott000** [microsoft/navcontainerhelper#540]
Getting this error:

```
Initialization of container BC15Preview failed
At C:\Users\todd.scott\Documents\WindowsPowerShell\Modules\navcontainerhelper\0.6.2.0\ContainerHandling\Wait-NavContainerReady.ps1:45 char:17
+ ...             throw "Initialization of container $containerName failed" ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Initialization ...5Preview failed:String) [], RuntimeException
    + FullyQualifiedErrorId : Initialization of container BC15Preview failed
```
I vaguely remember some switch that "forced" the load of the NAV client but can't find a reference and have tried a few different combinations.

Any help would be appreciated.

This is the script I am using:
```
$imageName = "bcinsider.azurecr.io/bcsandbox-master:gb-ltsc2016"
$containerName = "BC15Preview"
$auth = "UserPassword"
$licenseFile = "C:\Licenses\DevLicence-BC.flf"

New-NavContainer `
    -containerName $containerName `
    -accept_eula `
    -assignPremiumPlan `
    -auth $auth `
    -enableSymbolLoading `
    -imageName $imageName `
    -includeAL `
    -isolation process `
    -licenseFile $licenseFile `
    -restart no `
    -shortcuts Desktop `
    -updateHosts `
    -useBestContainerOS
```
This is the output:

> Login Succeeded
> NavContainerHelper is version 0.6.2.0
> Host is Microsoft Windows 10 Pro - ltsc2019
> Docker Client Version is 19.03.1
> Docker Server Version is 19.03.1
> Using image bcinsider.azurecr.io/bcsandbox-master:gb-ltsc2016
> Removing container BC15Preview
> Removing BC15Preview from hosts
> Removing C:\ProgramData\NavContainerHelper\Extensions\BC15Preview
> Creating Container BC15Preview
> Using license file C:\Licenses\DevLicence-BC.flf
> Version: 15.0.34648.0-gb
> Platform: 15.0.34329.0
> Generic Tag: 0.0.9.9
> Container OS Version: 10.0.14393.3025 (ltsc2016)
> Host OS Version: 10.0.17763.615 (ltsc2019)
> A better Generic Container OS exists for your host (ltsc2019)
> Using generic image mcr.microsoft.com/dynamicsnav:generic-ltsc2019
> Generic Container OS Version: 10.0.17763.615 (ltsc2019)
> Generic Tag of better generic: 0.0.9.91
> Using process isolation
> Creating container BC15Preview from image mcr.microsoft.com/dynamicsnav:generic-ltsc2019
> bfab58f36e936a2d3ba8cbeef881d4acd6b744e4011d6452ca4cb50d0419adf0
> Waiting for container BC15Preview to be ready
> Installing Business Central
> Installing Url Rewrite
> Installing OpenXML
> Installing DotNetCore
> Starting Local SQL Server
> Starting Internet Information Server
> Copying Service Tier Files
> Copying Web Client Files
> Copying Client Files
> Copying ModernDev Files
> Cannot find path 'C:\NAVDVD\ModernDev\program files\Microsoft Dynamics NAV' because it does not exist.
> at <ScriptBlock>, C:\Run\navinstall.ps1: line 69
> at <ScriptBlock>, C:\Run\start.ps1: line 114
> at <ScriptBlock>, <No file>: line 1Error
> Installing Business Central
> Installing Url Rewrite
> Installing OpenXML
> Installing DotNetCore
> Starting Local SQL Server
> Starting Internet Information Server
> Copying Service Tier Files
> Copying Web Client Files
> Copying Client Files
> Copying ModernDev Files
> Cannot find path 'C:\NAVDVD\ModernDev\program files\Microsoft Dynamics NAV' because it does not exist.
> at <ScriptBlock>, C:\Run\navinstall.ps1: line 69
> at <ScriptBlock>, C:\Run\start.ps1: line 114
> at <ScriptBlock>, <No file>: line 1
>

**Comment by freddydk** [comment]
I think I know what’s wrong here. It will be fixed in an hour or so

Få Outlook til iOS<https://aka.ms/o0ukef>
________________________________
Fra: GreatScott000 <notifications@github.com>
Sendt: Thursday, August 1, 2019 12:14:02 PM
Til: microsoft/navcontainerhelper <navcontainerhelper@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Emne: [microsoft/navcontainerhelper] Cannot find path 'C:\NAVDVD\ModernDev\program files\Microsoft Dynamics NAV' because it does not exist. (#540)


Getting this error:

Initialization of container BC15Preview failed
At C:\Users\todd.scott\Documents\WindowsPowerShell\Modules\navcontainerhelper\0.6.2.0\ContainerHandling\Wait-NavContainerReady.ps1:45 char:17
+ ...             throw "Initialization of container $containerName failed" ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Initialization ...5Preview failed:String) [], RuntimeException
    + FullyQualifiedErrorId : Initialization of container BC15Preview failed


I vaguely remember some switch that "forced" the load of the NAV client but can't find a reference and have tried a few different combinations.

Any help would be appreciated.

This is the script I am using:

$imageName = "bcinsider.azurecr.io/bcsandbox-master:gb-ltsc2016"
$containerName = "BC15Preview"
$auth = "UserPassword"
$licenseFile = "C:\Licenses\DevLicence-BC.flf"

New-NavContainer `
    -containerName $containerName `
    -accept_eula `
    -assignPremiumPlan `
    -auth $auth `
    -enableSymbolLoading `
    -imageName $imageName `
    -includeAL `
    -isolation process `
    -licenseFile $licenseFile `
    -restart no `
    -shortcuts Desktop `
    -updateHosts `
    -useBestContainerOS


This is the output:

Login Succeeded
NavContainerHelper is version 0.6.2.0
Host is Microsoft Windows 10 Pro - ltsc2019
Docker Client Version is 19.03.1
Docker Server Version is 19.03.1
Using image bcinsider.azurecr.io/bcsandbox-master:gb-ltsc2016
Removing container BC15Preview
Removing BC15Preview from hosts
Removing C:\ProgramData\NavContainerHelper\Extensions\BC15Preview
Creating Container BC15Preview
Using license file C:\Users\todd.scott\OneDrive - EVOLVE IMS\EvolveIMS\Licenses_Current\DevLicence-BC.flf
Version: 15.0.34648.0-gb
Platform: 15.0.34329.0
Generic Tag: 0.0.9.9
Container OS Version: 10.0.14393.3025 (ltsc2016)
Host OS Version: 10.0.17763.615 (ltsc2019)
A better Generic Container OS exists for your host (ltsc2019)
Using generic image mcr.microsoft.com/dynamicsnav:generic-ltsc2019
Generic Container OS Version: 10.0.17763.615 (ltsc2019)
Generic Tag of better generic: 0.0.9.91
Using process isolation
Creating container BC15Preview from image mcr.microsoft.com/dynamicsnav:generic-ltsc2019
bfab58f36e936a2d3ba8cbeef881d4acd6b744e4011d6452ca4cb50d0419adf0
Waiting for container BC15Preview to be ready
Installing Business Central
Installing Url Rewrite
Installing OpenXML
Installing DotNetCore
Starting Local SQL Server
Starting Internet Information Server
Copying Service Tier Files
Copying Web Client Files
Copying Client Files
Copying ModernDev Files
Cannot find path 'C:\NAVDVD\ModernDev\program files\Microsoft Dynamics NAV' because it does not exist.
at , C:\Run\navinstall.ps1: line 69
at , C:\Run\start.ps1: line 114
at , : line 1Error
Installing Business Central
Installing Url Rewrite
Installing OpenXML
Installing DotNetCore
Starting Local SQL Server
Starting Internet Information Server
Copying Service Tier Files
Copying Web Client Files
Copying Client Files
Copying ModernDev Files
Cannot find path 'C:\NAVDVD\ModernDev\program files\Microsoft Dynamics NAV' because it does not exist.
at , C:\Run\navinstall.ps1: line 69
at , C:\Run\start.ps1: line 114
at , : line 1

**Comment by GreatScott000** [comment]
Thanks @freddydk, love the turn around on your issues.  Not always this fast but always responsive.  Love it.

**Comment by freddydk** [comment]
If you remove the -ltsc2016 from the imagename, then you will automatically download the container version which matches your OS best - and in your case it is ltsc2019 (which are half the size of ltsc2016 images).
That would also be must faster, and the problem would be resolved.
If you want to keep your ltsc2016 image - you would need to (once) add -alwaysPull to your command to ensure the download of a new generic image (just published) which solves this problem.

BTW - if your images takes up a lot of space, there is a function in docker desktop to restore to default - this removes all images

**Comment by GreatScott000** [comment]
okay, removing the -ltsc2016 worked, thank you.

Were can I get a "compatible" licence?  Is there a 15 option in PBSC?

**Comment by freddydk** [comment]
Nope, not yet.
But just ignore the warning for now.

**Comment by GreatScott000** [comment]
Thanks, you can close this now.
