### ISSUE TITLE
bcinsider.azurecr.io/bcsandbox cannot be pulled : unauthorized: authentication required

### ISSUE THREAD

**Issue by chavansachin20** [microsoft/navcontainerhelper#561]
Hi all,

we e used to create containers with normal images pulled from `docker pull mcr.microsoft.com/businesscentral/sandbox:update26-us-ltsc2016` but now we want to use BCinseder images for future development. facing issue while pulling images from `docker pull bcinsider.azurecr.io/bcsandbox:us` command. Can anyone help here get authorise to this command steps to download the image from bcinsider?

**Error details**: 

> PS C:\WINDOWS\system32> docker pull bcinsider.azurecr.io/bcsandbox:us
docker : Error response from daemon: Get https://bcinsider.azurecr.io/v2/bcsandbox/manifests/us: unauthorized: authentication required
At line:1 char:1
> + docker pull bcinsider.azurecr.io/bcsandbox:us
> + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>    + CategoryInfo          : NotSpecified: (Error response ...cation required:String) [], RemoteException
>    + FullyQualifiedErrorId : NativeCommandError
 
![image](https://user-images.githubusercontent.com/5293496/63146073-55562300-c017-11e9-8a94-67c8e6440bcc.png)

Thanks 
Sachin Chavan

**Comment by chavansachin20** [comment]
@freddydk / @waldo1001 :  can you please help to resolve this issue.

**Comment by freddydk** [comment]
Are you serious?

You file an issue and 8 minutes after - you ping people to get your issue resolved faster?
I try to answer issues here as fast as possible, but to be honest, I see this behavior as rude.

Having said that...
Look at the error - authentication required.
I think you need to authenticate.
If you already did - then you might have used wrong credentials (they were changes x months ago, meaning you probably are not in a hurry here)
Since you are using bcinsider - you get credentials through collaborate and you also find the explanation there on how to authenticate.

In the future, please allow people at least 24 hours to respond before pinging people when filing something on github.

**Comment by freddydk** [comment]
It is even explained here where you get the credentials https://freddysblog.com/2019/07/31/preview-of-dynamics-365-business-central-2019-release-wave-2/

**Comment by chavansachin20** [comment]
To resolve error : **unauthorized: authentication required** 

try to use **VS code PowerShell** rather than normal PowerShell

use below command 
`docker login "bcinsider.azurecr.io"`

and here use **bcinsider credentials** (Username & Password) which you have received from Collaborate
