### ISSUE TITLE
Introduction of Sync-NAVApp -Mode BaseAppUpgrade? 

### ISSUE THREAD

**Issue by plagijat** [microsoft/navcontainerhelper#611]
While converting our C/AL solution to Customized BaseApp solution using Freddy's article [C/AL to AL code customizations](https://freddysblog.com/2019/04/15/c-al-to-al-code-customizations/) after the new Customized Base App has been published with Publish-NewApplicationToNavContainer **all data is lost**. This is due to usage of -useCleandatabase flag which removes al C/AL objects (including tables with data) before publishing new Customized Base App.

Is there a milestone planned where a new command `Sync-NAVApp -Mode BaseAppUpgrade` is introduced so that the syncing of the old C/AL tables to new AL tables is done during publishing new Customized Base App?

`Sync-NAVApp -Mode BaseAppUpgrade` -> [Support for performant data upgrade from C/AL tables to AL tables](https://docs.microsoft.com/en-us/dynamics365-release-plan/2019wave2/dynamics365-business-central/support-performant-data-upgrade-cal-tables-al-tables)

Thanks,
Zoran M.

**Comment by freddydk** [comment]
Yes, we will look into this within the next ~week.

**Comment by freddydk** [comment]
It was implemented in a different way.
https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/upgrade/upgrade-technical-upgrade-v14-v15

**Comment by fvet** [comment]
@freddydk 

I ended up here, since there's only limited information on the 'Sync-NAVApp -Mode BaseAppUpgrade' feature (besides https://www.yammer.com/dynamicsnavdev/#/Threads/show?threadId=293479454646272). It seems not included in Dynamics 365 Business Central 2019 Release Wave 2.W1.36649 DVD. (not using Docker)

I've tested the following scenario : BC 14 database with one custom table 'MyTable1'

Running through the standard upgrade scripts (https://docs.microsoft.com/nl-be/dynamics365/business-central/dev-itpro/upgrade/upgrade-unmodified-application), the database is converted smoothly via Sync-NAVApp, and upon installing the new BC 15 extension with the 'MyTable1' object, the table is renamed on SQL (suffixed with the AppId) and data is retained. Cool!

Second scenario : BC 14 database with one custom table 'MyTable1'. For the new BC 15 extension, we need to adopt the new **prefix** naming and will **rename** the table object to '**XXX** MyTable 1' (keeping the same object ID however)

Running through the standard upgrade scripts (https://docs.microsoft.com/nl-be/dynamics365/business-central/dev-itpro/upgrade/upgrade-unmodified-application), the database conversion fails on the Sync-NAVApp step

> Unsupported table change. Table:MyTable; Change:Remove

Some questions:
- Is the only solution to fix the above to rename the objects in C/AL (BC 14) first before doing the database upgrade ? Or can we expect some tooling that will support the same as in scenario id, not only using the same Object Name, but also respecting the same object id while renaming the SQL tables (suffixing with the AppId and prefixing with the App prefix (or suffix)?
- Is _-Mode BaseAppUpgrade_ no longer needed?
- What is _-PrepareCalToAlUpgrade_ on the Sync-NAVTenant

**Comment by freddydk** [comment]
I don't know much about upgrade.
I know that the baseappupgrade is not implemented and not needed.
Have never heard about preparecaltoalupgrade
and on the other, I do have a session at Tech Days in a few weeks with Nikola Kukrika, where I expect a lot of these questions to be answered.
Yammer is a better place to answer these questions than here - this is only for docker related issues.
thanks
