### ISSUE TITLE
[Sync-BCContainerApp] expose -Force parameter ?

### ISSUE THREAD

**Issue by JulienDecottignies** [microsoft/navcontainerhelper#691]
Hi,

Is it possible to expose the -Force parameter in the Sync-BCContainerApp function ?

For a certain case in my Azure DevOps Pipeline I need to use this function in Clean Mode, problem is powershell prompts user to confirm, so my Pipeline fails.
I didn't find any other alternative than making a copy of the script Sync-NavContainerApp of this repo and add the Force parameter by myself, then I call this script instead of Sync-BCContainerApp from this module.

_[in my copy of Sync-NavContainerApp]_
```
(...)
 $parameters += @{"Force" = $true}
        
        Sync-NavApp @parameters
```

Is there any better way to do that ? If not, is it possible to add this parameter to this function ?

Thanks a lot!

**Comment by freddydk** [comment]
You can just use invoke-scriptinnavcontainer directly in your ci script and call sync-navapp in that. No need to create a new function

Hent Outlook til iOS<https://aka.ms/o0ukef>
________________________________
Fra: jdecottignies <notifications@github.com>
Sendt: Thursday, October 24, 2019 12:42:57 PM
Til: microsoft/navcontainerhelper <navcontainerhelper@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Emne: [microsoft/navcontainerhelper] [Sync-BCContainerApp] expose -Force parameter ? (#691)


Hi,

Is it possible to expose the -Force parameter in the Sync-BCContainerApp function ?

For a certain case in my Azure DevOps Pipeline I need to use this function in Clean Mode, problem is powershell prompts user to confirm, so my Pipeline fails.
I didn't find any other alternative than making a copy of the script Sync-NavContainerApp of this repo and add the Force parameter by myself, then I call this script instead of Sync-BCContainerApp from this module.

[in my copy of Sync-NavContainerApp]

(...)
 $parameters += @{"Force" = $true}

        Sync-NavApp @parameters


Is there any better way to do that ? If not, is it possible to add this parameter to this function ?

Thanks a lot!
