### ISSUE TITLE
Error- "Your program license doesn't allow you to publish 'AL Test Suite'."

### ISSUE THREAD

**Issue by syssolmarketing** [microsoft/navcontainerhelper#718]
We are testing our BC apps for Business Central 15 in a sandbox, image tag mcr.microsoft.com/businesscentral/sandbox:us

We can't access the AL Test Suite. Which license do we need to access this or is there in an error in the way we are trying to access the tool. Below is a screen grab of the error.

![TestToolKit Error](https://user-images.githubusercontent.com/54630609/68245453-fa641480-ffe4-11e9-9fc4-f023ebb7ba86.png)

**Comment by freddydk** [comment]
The CRONUS license on the docker image doesn't work - you will need to specify your developer license. I would guess that any partner 15.x license would work.

**Comment by syssolmarketing** [comment]
The only 15.x license file I could create in the LKC tool was for "Microsoft Dynamics 365 Business Central on premises" still no luck. 

The NAV Perpetual license file we were using (and got the above error from) does not have a version newer than 2018

**Comment by freddydk** [comment]
Please copy/paste the script used and the full end2end output here.

**Comment by syssolmarketing** [comment]
How do I get the Partner Workshop License? I don't see that option in the LKC Tool.

**Comment by freddydk** [comment]
That is in Partnersource somewhere - I don't know where and I also don't know the LKC tool so I am of little help here.

**Comment by freddydk** [comment]
I stand corrected, the global training licenses are not in Partnersource.
I have uploaded a package to http://aka.ms/Collaborate - same location as you get insider builds.
Should be available within a few hours.

**Comment by syssolmarketing** [comment]
Thanks Freddy. I am new to this portal I have an account and can see the package screen. How do I find the correct package? search doesn't seem to bring up any results.

**Comment by freddydk** [comment]
Do you have access to insider builds - it is in the same location.
If not, email dyn365bep@microsoft.com and request access.

**Comment by JeremyVyska** [comment]
Small addendum in case anyone ends up on this issue like I did:

If you're running into this issue, and you're absolutely sure you're running on the right license, triple check.  Powershell into the container and export the NAV License.

I had an unspotted typo or something in a container script.  I was getting this exact same issue about permissions on importing.  I regenerated my dev license, everything.  Turned out, the container was still on the CRONUS license.

If you're sure you don't have a typo in the path, try making the path & filename short as possible, like C:\_bc\docker.flf or some such.

I never got any licensing related errors in the 10 times I built the container, only when adding the -includeTestToolkit flag.
