### ISSUE TITLE
Suggestion for the build containers

### ISSUE THREAD

**Issue by gintuoklis** [microsoft/navcontainerhelper#754]
Hey @freddydk, 
One suggestion for the navcontainerhelper. Could you please implement _'reuse'_ feature using _docker commit_, instead of restoring bak file. It should drastically improve the build time. 

Best Regards, 
Gintautas

**Comment by git-no** [comment]
What seems missing in _navcontainerhelper_ is the image handling like in the docker philosophy.
And _navcontainerhelper_ is slow in starting container. The reason is it is a wrapper around docker with a lot of scripting, helping people without having advanced docker know how. This is one of the advantages.

On the other hand everybody can maintain docker images himself can create images from container anytime. This is standard in docker with `docker commit`.
For what do you need `New-NavContainer` if you can use `docker run` of a self generate image!?

By the way, it is not a good concept to have a database (file) within a docker container (maybe only for test or development circumstances).  The database file should live on a host for performance and lifecycle reasons. A docker container is by definition disposable and should creatable fast.

**Comment by freddydk** [comment]
I would say that it is not a good concept to have data within a docker container.
The Business Central containers comes with all in order to make them easy to use to AL development. The container itself is disposable as it is only used as an engine.
If you decide to use a database server outside the Business Central container, the SQL Server inside the container is never started and doesn't take up any memory nor CPU cycles, so with the current setup you have both options.
New-NavContainer is not created for docker experts - it is created for people who need to use docker without having to learn about docker in details (and there are 1000s of those in the community) and this of course comes with a penalty. It does however also come with a lot of benefits. Docker experts can use docker run, docker commit, docker build with DOCKERFILES etc. as they see fit.

**Comment by gintuoklis** [comment]
Hey Guys, 
Sorry my first post was not clear enough. My comment was is in relation to build pipelines & reuseContainer setting from your project: https://dev.azure.com/businesscentralapps/HelloWorld

Sorry for writing on the different project, but there's not way to give feedback there.

In general pipelines takes 5-6 minutes to run, which in mine opinion should be way no more that 2minutes. By implementing it with _docker commit_, and _docker run_, could greatly increase build time. 

I wonder do you use the same build scripts for development @ MS. Does it take the same time? What specs you have on the buildagent machine?

**Comment by freddydk** [comment]
Our CI pipelines takes hours and you will find that you would only be able to keep your pipelines down to a few minutes if you have a very small project and no or few tests.
If you try docker commit and docker run - I think you will find that it isn't any faster than starting a new container.
If you think about it, the Business Central containers are more or less just stopped containers we restart.
Running the generic image (or even a windows servercore image) with a DVD image and a DOCKERFILE would be more like the "real" docker way - which would take a lot more time.
I am constantly looking at ways to increase performance, but I don't think docker commit / docker run is the answer, sorry.
