### ISSUE TITLE
docker-compose

### ISSUE THREAD

**Issue by yrest** [microsoft/navcontainerhelper#768]
Hi Freddy,

Just wondering if there are any recommendations for BC through docker-compose?

Thanks.

**Comment by freddydk** [comment]
No
Docker compose is typically used to start multiple connected containers (as far as I know) and since the NAV/BC containers contains everything and compose shouldn't be needed.
If you want to seperate Database, it is my assumption that you typically would setup the Database server on a separate machine or directly on the host.
