### ISSUE TITLE
Printing does not work

### ISSUE THREAD

**Issue by Spycoclown** [microsoft/navcontainerhelper#782]
I try to print the order confirmation, but it does not work.
![image](https://user-images.githubusercontent.com/7090519/70617162-44599f00-1c10-11ea-9052-d9245882842c.png)

I can press "sent to" but if i press the "print" button it happens nothing.

I hear it is because in the container there is missing a default printer service.

**Comment by freddydk** [comment]
What image are you using, what version of windows are you running and what isolation?

We build our containers on ServerCore and that doesn't have the printing server role.
https://docs.microsoft.com/en-us/virtualization/windowscontainers/deploy-containers/print-spooler

Not since 1803:
https://docs.microsoft.com/en-us/windows-server/administration/server-core/server-core-container-removed-roles

But... I would assume that it should work if you use ltsc2016 (then the container should have spooler service) or if you use process isolation (-useBestContainerOS)

Tried with process isolation on my machine:
![image](https://user-images.githubusercontent.com/10775043/70618547-73254480-1c13-11ea-99c5-acf96c548aec.png)

Tried with hyperv isolation on my machine:
Works as well.

what are you running? script and output please

**Comment by freddydk** [comment]
Please provide more information and reopen the issue if it still persists,

**Comment by gintuoklis** [comment]
Hey @freddydk, 

We are trying to setup printer on bc container, but cannot get it working. 
Business scenario is the following: we are trying to documents using job queue. Warehouse labels and etc...
Easiest way to test, is to check for Printer Name on Job Queue Entry Card. If you drill down on Printer Name, it tries to list down printers installed on the server side (inside container).

![image](https://user-images.githubusercontent.com/16342128/142406871-157c83a6-b617-4e2e-8ae6-9189846b266c.png)

Of course it fails, since container does not have spooler service running/installed. 
if we try to install it, we get an error

![image](https://user-images.githubusercontent.com/16342128/142406995-bafa1652-7861-47e6-ba1b-3b11d36bd679.png)

My host OS version
![image](https://user-images.githubusercontent.com/16342128/142407069-9b7859b8-d9ff-42c6-bfab-57fb4a1575ce.png)

My container OS version

![image](https://user-images.githubusercontent.com/16342128/142407098-8bc5ab96-3e3a-468a-a645-052616d16de3.png)


Any suggesiton/advice?

Best Regards, 
Gintautas
