### ISSUE TITLE
External SQL credentials ignored when using NavUserPassword.

### ISSUE THREAD

**Issue by SShadowS** [Microsoft/navcontainerhelper#80]
When using this:
`$DatabaseCredential = Get-Credential`

`New-NavContainer -containerName ExSQLTest -accept_eula -auth NavUserPassword -databaseCredential $DatabaseCredential -databaseName ExSQLTest -databaseServer 192.168.2.22 -includeCSide -memoryLimit 4G -updateHosts -licenseFile 'X:\NAV2018.flf' -imageName microsoft/dynamics-nav:2018-dk`

Then it will use SA and the password from NavUserPassword, instead of the supplied SQLCredentials.
It works fine if you use Windows Auth, but can't in this setup and dont want everyone to have SA password.

**Comment by freddydk** [comment]
Have you tried specifying the username/password for your NAV user (-credential $navcredential) ?
It might be the random generation of password, which causes this.

**Comment by SShadowS** [comment]
If you specify `-auth NavUserPassword` but dont supply one with `-credential $navcredential`, it will ask you for it.
So I am already using it. 
And it is the password of that NavUser credential it uses towards the SQL instead of the SQL Credentials.

Ex. I type these as credentials:
SQLCrendential = SQLUSer \ SQLPassword
NAVCredential = NAVUSer \ NAVPassword

It the tries to connect to the SQL with **sa** and **NAVPassword**.

Will try with explicit credentials tomorrow. But still, the existing doc is wrong or this is just a undocumented "feature". ;)

**Comment by freddydk** [comment]
I am only suggesting things because I cannot repro your issue.
This code works for me:

$cred1 = New-Object System.Management.Automation.PSCredential ( "nav1", (ConvertTo-SecureString -String "P@ssword1" -AsPlainText -Force) )
$cred2 = New-Object System.Management.Automation.PSCredential ( "nav2", (ConvertTo-SecureString -String "P@ssword2" -AsPlainText -Force) )
$sqlcred = New-Object System.Management.Automation.PSCredential ( "sa", $Cred1.Password )

New-NavContainer -accept_eula `
                 -containerName test `
                 -Credential $Cred1 `
                 -useSSL:$false `
                 -auth NavUserPassword `
                 -imageName "microsoft/dynamics-nav" `
                 -updateHosts

New-NavContainer -accept_eula `
                 -containerName test2 `
                 -Credential $Cred2 `
                 -useSSL:$false `
                 -auth NavUserPassword `
                 -imageName "microsoft/dynamics-nav" `
                 -databaseServer test `
                 -databaseInstance SQLEXPRESS `
                 -databaseName CRONUS `
                 -databaseCredential $sqlcred `
                 -updateHosts

where test2 uses the credentials provided in sqlcred to connect to test.
if you could provide docker logs for the 2 containers or a repro (like the one I just provided), then I will try to solve the issue.

**Comment by SShadowS** [comment]
I will try tomorrow, if you cant reproduce it, it must be at my end. I will close this ticket and create a new one with more info if needed.
