### ISSUE TITLE
Traefik and PublicDomainName not carried to every setting

### ISSUE THREAD

**Issue by jonwrede** [microsoft/navcontainerhelper#825]
We are running Traefik as a Gateway for multiple BC/NAV Containers. 
There is a problem with the publicDomainName setup within the container.
Given following properties:
- publicDomainName = "example.com"
- containerName = "test"

The container is accessible under "example.com/test" but the path is not carried into the container. 
For everything but the download section this works fine. But if one is trying to download any file the list page is shown as expected. But in the path in the top is off. The path is given as "example.com - /" and all files are trying to be downloaded directly from example.com for example "https://example.com/al-3.0.193882.vsix" where it cannot be found. 
Steps to reproduce 

1. Run Setup-TraeficContainerForBCContainer -PublicDnsName "example.com" -ContactEMailForLetsEncrypt "test@example.com"
2. Run New-NavContainer -publicDnsName "example.com" -useTraefik

![Screenshot_2020-01-24](https://user-images.githubusercontent.com/50319059/73071633-93ebe580-3eb3-11ea-967a-bc18c3818598.png)

**Comment by tfenster** [comment]
That is a known issue which unfortunately can't easily be fixed. You would have to use https://example.com/testdl/al-3.0.193882.vsix to get that file. The VM landing page (if created using the ARM templates provided by Microsoft e.g. https://aka.ms/getbc)

**Comment by jonwrede** [comment]
The issuse makes ClickOnce unusable. Which makes the docker images for any "productive" development enviroments unusable. Any leads on how to fix it? I might pursue it myself.

**Comment by freddydk** [comment]
So the issue is not the .vsix file - the issue is that the clickonce manifest is created wrongly and cannot be used. I can have a look to see whether there is a way to fix that.

**Comment by jonwrede** [comment]
@freddydk Yes, the whole container "thinks" its reachable under the in publicDnsName given domain. While it ist actually accessible under publicDnsName/<containername>when run with useTraefik.
The problem is that the nav-container is not aware that it is accessible behind a Traefik instance. Maybe switching to relative paths could fix the problem. But they might not work with a ClickOnce installer. In that case there would need to be a second ClickOnce for running through a traefik instance. 
A fix would be much appreciated.

**Comment by freddydk** [comment]
I will have a look

**Comment by freddydk** [comment]
I can see that we looked at this when we implemented this - the arm templates are just disabling traefik and the arm templates. They write:

10:48:48 AM ClickOnce specified, cannot add Traefik

I will double check whether it is possible to support it.

**Comment by freddydk** [comment]
The problem here is, that Windows Client uses a proprietary protocol for communicating with the service tier, and that one cannot travel through traefik, which only supports http and https.
CSIDE also cannot reach the SQL Server inside the container through traefik.
This is the reason why we didn't bother making the clickonce manifest download - it won't work if you manage to get the manifest installed.
Traefik works really well for VS Code and AL extension development towards BC and WebClient - not so good when using CSIDE and Windows Client.
You will have to allocate different ports to different containers - specifying the port you want the container to listen on for the various services and you probably need to use port mapping for the SQL Server. It is my experience that if you open SQL Server ports on the internet, you will be subject to port scanning and a lot of attempts to attack the port.

**Comment by jonwrede** [comment]
@freddydk Thanks for your quick response. I think it might be a good idea to enable CSIDE support anyway, would make development/support of legacy systems that much easier.

A possible solution could be to use traefik not only as a http router but also as a tcp router. One would then need to use domains for multiplexing instead of the paths. That could be done by pointing a wildcard domain at the target server. Then traefik could use the subdomain to point to different containers and passthrough all the needed ports. This would also fix the initial issuse. The publicDnsName could be set the subdomain which is pointed to the container.

Why would you need a port mapping to the sql server? In production ClickOnce deployment the SQL Server is not passthrough.

**Comment by tfenster** [comment]
@jonwrede TCP for Traefik came along after the Traefik support in nch was implemented, so that would probably work and I personally have it on my list of things to actually try and improve the nch, but if you are quicker, all the better :) I also tried to implement the wildcard setup and failed but can't exactly remember why.

**Comment by freddydk** [comment]
@jonwrede - if you want to try it out - all you need to do is to download this file:
`https://github.com/microsoft/nav-docker/blob/master/generic/Run/130/SetupClickOnce.ps1
`and modify $clickOnceWebSiteUrl to point to the location like:
`$clickOnceWebSiteUrl = "https://${publicDnsName}/$hostname/NAV"
`and then specify your new SetupClickOnce.ps1 in -myscripts to new-navcontainer.
This will replace the SetupClickOnce of the container with your new file and should make the manifest work.
