### ISSUE TITLE
updateHosts switch gets an error

### ISSUE THREAD

**Issue by Rukkulakki** [microsoft/navcontainerhelper#828]
PS C:\Windows\system32> New-NavContainer -containerName CustomerInstall -accept_eula -accept_outdated -auth Windows -Credential sh -doNotExportObjectsToText -imageName microsoft/dynamics-nav:2018-rtm-dk -includeCSide -shortcuts DesktopFolder -updateHosts CustomerInstall

NavContainerHelper is version 0.6.4.25
NavContainerHelper is running as administrator
Host is Microsoft Windows 10 Enterprise - 1909
Docker Client Version is 19.03.5
Docker Server Version is 19.03.5
Using image microsoft/dynamics-nav:2018-rtm-dk-ltsc2019
Get-Item : Cannot find path 'C:\Windows\system32\CustomerInstall\ServiceTier\program files\Microsoft Dynamics NAV' because it does not exist.
At C:\Program Files\WindowsPowerShell\Modules\navcontainerhelper\0.6.4.25\ContainerHandling\New-NavContainer.ps1:559 char:28
+ ... vversion = (Get-Item -Path "$dvdPath\ServiceTier\program files\Micros ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Windows\syst...ft Dynamics NAV:String) [Get-Item], ItemNotFoundException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.GetItemCommand

Running without the -updateHosts works

**Comment by freddydk** [comment]
Do you have a customerinstall word after the -updatehosts? -updatehosts is a switch, nothing after that.

Hent Outlook til iOS<https://aka.ms/o0ukef>
________________________________
Fra: Svend Heinesen <notifications@github.com>
Sendt: Friday, January 31, 2020 1:36:01 PM
Til: microsoft/navcontainerhelper <navcontainerhelper@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Emne: [microsoft/navcontainerhelper] updateHosts switch gets an error (#828)


PS C:\Windows\system32> New-NavContainer -containerName CustomerInstall -accept_eula -accept_outdated -auth Windows -Credential sh -doNotExportObjectsToText -imageName microsoft/dynamics-nav:2018-rtm-dk -includeCSide -shortcuts DesktopFolder -updateHosts CustomerInstall

NavContainerHelper is version 0.6.4.25
NavContainerHelper is running as administrator
Host is Microsoft Windows 10 Enterprise - 1909
Docker Client Version is 19.03.5
Docker Server Version is 19.03.5
Using image microsoft/dynamics-nav:2018-rtm-dk-ltsc2019
Get-Item : Cannot find path 'C:\Windows\system32\CustomerInstall\ServiceTier\program files\Microsoft Dynamics NAV' because it does not exist.
At C:\Program Files\WindowsPowerShell\Modules\navcontainerhelper\0.6.4.25\ContainerHandling\New-NavContainer.ps1:559 char:28

  *   ... vversion = (Get-Item -Path "$dvdPath\ServiceTier\program files\Micros ...
  *

            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


     *   CategoryInfo : ObjectNotFound: (C:\Windows\syst...ft Dynamics NAV:String) [Get-Item], ItemNotFoundException
     *   FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.GetItemCommand

Running without the -updateHosts works

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmicrosoft%2Fnavcontainerhelper%2Fissues%2F828%3Femail_source%3Dnotifications%26email_token%3DACSGUA2ZGTENTJCBT5X47GLRAQLLDA5CNFSM4KOGL3KKYY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4IKEBEHA&data=02%7C01%7Cfreddy.kristiansen%40microsoft.com%7C67493c6cd4b74713104408d7a64a221b%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637160709640819019&sdata=ukmHu6yvLT3iMABGUSLLnVb8JC%2BPnPPptx1opqe6PR8%3D&reserved=0>, or unsubscribe<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FACSGUA2ZPDFZBTQUU47VEADRAQLLDANCNFSM4KOGL3KA&data=02%7C01%7Cfreddy.kristiansen%40microsoft.com%7C67493c6cd4b74713104408d7a64a221b%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637160709640828984&sdata=cVMkFlOk8%2B6%2FuQULydlQ2o0fVPtl%2FNUKN%2FwURnR8lhk%3D&reserved=0>.

**Comment by Rukkulakki** [comment]
I did Indeed have the CustomerInstall after as well. Works like a charm if only I use it correctly :)
