### ISSUE TITLE
Import-DeltasToNavContainer should take version from target

### ISSUE THREAD

**Issue by ajkauffmann** [Microsoft/navcontainerhelper#85]
The cmdlet Import-DeltasToNavContainer takes the version from the modified objects. As a result, you don't get the updated version numbers (e.g. CU1 version).

It would be better to get the version list from target.
Even better would be to have a merge version list function. (I guess @waldo1001 has an idea how to do that)

**Comment by waldo1001** [comment]
Well, I do use my own "Apply-NAVDelta" functions for that, where I add or remove a given versionlist ..
https://github.com/waldo1001/Cloud.Ready.Software.PowerShell/blob/master/PSModules/Cloud.Ready.Software.NAV/ModelTools/Apply-NAVDelta.ps1
https://github.com/waldo1001/Cloud.Ready.Software.PowerShell/blob/master/PSModules/Cloud.Ready.Software.NAV/ModelTools/Apply-NAVDelta2.ps1

**Comment by freddydk** [comment]
I will put this on the backlog...

**Comment by freddydk** [comment]
I did not change this yet.
I did add a filter parameter to Convert-ModifiedObjectsToAl and Export-ModifiedObjectsAsDeltas to allow you to run with full object sets (set filter to empty string) instead of using modified=1.
No plans to change any further. Feel free to submit a pull request if you have any improved functionality in mind.
