### ISSUE TITLE
Running test using Run-TestsInNavContainer runs only part of test suite

### ISSUE THREAD

**Issue by Phillers** [microsoft/navcontainerhelper#938]
I have a suite with several test codeunits, I can run all of them manually.
When I try to run them using script - both on pipeline and manually - it does not run all of them. Using Get-TestsFromNavContainer shows the list including the skipped tests:
![obraz](https://user-images.githubusercontent.com/10747014/78677923-983b7280-78e8-11ea-81a3-536d425367ce.png)
![obraz](https://user-images.githubusercontent.com/10747014/78677988-abe6d900-78e8-11ea-800b-e31328cf63a3.png)

Is there something I am missing? How to run whole suite by script

**Comment by freddydk** [comment]
How do you populate the test suite?
You could try to include -debugmode and send me the full output (might reveal some info)

but... - in 15.x and later the recommendation is to run tests using the -extensionid <appid> instead of testsuite. This way you also don't have to populate the testsuite yourself.

**Comment by Phillers** [comment]
The test suite is populated onInstall, using following function (based on MyNAVBlog about pipelines):
![obraz](https://user-images.githubusercontent.com/10747014/78760910-2283e500-7982-11ea-910d-9e2f00ccca31.png)
the debugMode doeasn't seem to produce any additional output since all tests are succesful.
How should I use the extensionId parameter? It throws an error both when I used the app id and name:
![obraz](https://user-images.githubusercontent.com/10747014/78762915-cc647100-7984-11ea-8bf6-5979e1c70212.png)
![obraz](https://user-images.githubusercontent.com/10747014/78762948-d9816000-7984-11ea-8e5c-541a91503bfc.png)

**Comment by freddydk** [comment]
Are you using the CAL Test tool (looking at your code unit)?
Did you read this: https://freddysblog.com/2019/10/22/running-tests-in-containers-2/
Which explains the changes in 15.x and how to include the AL Test Tool.
The C/AL Test Tool will eventually go away.

Also if you are running a local version of 16.x you need a newer NavCOntainerHelper due to this https://freddysblog.com/2020/04/02/running-tests-on-business-central-16-0/

**Comment by Phillers** [comment]
No, it's just old variable name - it is the Test Method Line table
I use newest version of helper

**Comment by freddydk** [comment]
What container image are you using?
Could you post the output of the container generation?
Thanks

**Comment by Phillers** [comment]
Default latest onprem, before 16.0 it worked the same
[log.txt](https://github.com/microsoft/navcontainerhelper/files/4450200/log.txt)

**Comment by freddydk** [comment]
I am sorry, but I really need something (end 2 end scripts) with which I can repro this, else I will be spending hours and hours trying to get this to fail.
If by any chance you can email me a script and maybe an .app file with which I can repro this, then I can have a look.

**Comment by freddydk** [comment]
I think I found a reason why this might be failing.
The next containerhelper contains a fix, which might solve this (issue #944)
If not, then the next containerhelper will (using -debugMode) add a lot of debug info to the output, which should give me a better chance to see what's wrong.

**Comment by freddydk** [comment]
Shipped in 0.6.5.7

**Comment by Phillers** [comment]
debugMoode doesn't seem to add any additional output, problem still occurs
![obraz](https://user-images.githubusercontent.com/10747014/80974154-a5cd1500-8e20-11ea-8fde-1c0de4e29178.png)

**Comment by freddydk** [comment]
Try to run the same where PowerShell is running as administrator.
